-- Real PostgreSQL RLS tests, synthetic identities, disposable CI database only.
\set ON_ERROR_STOP on
begin;
create schema fk_test;
grant usage on schema fk_test to authenticated,anon;
create function fk_test.ok(value boolean,label text) returns void language plpgsql as $$ begin if value is distinct from true then raise exception 'FAIL: %',label; end if; raise notice 'PASS: %',label; end $$;
create function fk_test.denied(statement text) returns boolean language plpgsql as $$ begin execute statement; return false; exception when insufficient_privilege then return true; end $$;
create function fk_test.rejected(statement text) returns boolean language plpgsql as $$ begin execute statement; return false; exception when others then return true; end $$;
insert into auth.users values('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222'),('33333333-3333-4333-8333-333333333333');
insert into folkoop_private.pilots(user_id) select id from auth.users where id!='33333333-3333-4333-8333-333333333333';
select fk_test.ok((select count(*)=6 from pg_class where relname in ('fk_profiles','fk_communities','fk_memberships','fk_posts','fk_blocks','fk_reports') and relrowsecurity),'all tables use RLS');
set local role anon;
select fk_test.ok(fk_test.denied('select * from public.fk_profiles'),'anonymous cannot read profiles');
select fk_test.ok(fk_test.denied('select public.fk_create_community(''no'','''')'),'anonymous cannot mutate');
set local role authenticated;
select set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',true);
select fk_test.ok((select count(*)=0 from public.fk_profiles),'uninvited authenticated user sees nothing');
select fk_test.ok(fk_test.denied('select public.fk_create_community(''no'','''')'),'uninvited user cannot create');
select fk_test.ok(fk_test.denied('select * from folkoop_private.pilots'),'pilot list private');
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
select public.fk_save_profile('Alice','Repair','Private',false);
select fk_test.ok((select count(*)=1 from public.fk_profiles),'own private profile visible');
select fk_test.ok(fk_test.denied('update public.fk_profiles set listed=true'),'direct profile writes forbidden');
select public.fk_create_community('Workshop','A shared group') as cid \gset
select fk_test.ok((select count(*)=1 from public.fk_memberships),'owner membership created atomically');
select fk_test.ok(fk_test.denied('update public.fk_communities set owner_id=''22222222-2222-4222-8222-222222222222'''),'cannot forge ownership');
select public.fk_publish(:'cid','Alice first post') as pid \gset
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',true);
select public.fk_save_profile('Bob','Design','Visible',true);
select fk_test.ok((select count(*)=1 from public.fk_profiles),'Bob cannot see private Alice profile');
select fk_test.ok((select count(*)=1 from public.fk_communities),'pilot discovers groups');
select fk_test.ok((select count(*)=0 from public.fk_posts),'nonmember cannot read posts');
select fk_test.ok(fk_test.denied(format('select public.fk_publish(%L,''intrusion'')',:'cid')),'nonmember cannot post');
select fk_test.ok(fk_test.denied('insert into public.fk_memberships values(gen_random_uuid(),''11111111-1111-4111-8111-111111111111'',false)'),'cannot forge membership');
select public.fk_join(:'cid');select public.fk_join(:'cid');
select fk_test.ok((select count(*)=1 from public.fk_memberships),'double join idempotent; roster private');
select fk_test.ok((select count(*)=1 from public.fk_posts),'member reads posts');
select public.fk_delete_post(:'pid');
select fk_test.ok((select count(*)=1 from public.fk_posts),'member cannot delete other author');
select public.fk_publish(:'cid','Bob post') as bpid \gset
select public.fk_report(:'pid','Test report');
select fk_test.ok((select count(*)=1 from public.fk_reports),'reporter sees own report');
select public.fk_block('11111111-1111-4111-8111-111111111111',true);
select fk_test.ok((select count(*)=1 from public.fk_posts),'blocked author content hidden');
select public.fk_block('11111111-1111-4111-8111-111111111111',false);
select fk_test.ok((select count(*)=2 from public.fk_posts),'unhide restores content');
select public.fk_leave(:'cid');
select fk_test.ok((select count(*)=0 from public.fk_posts),'leaving revokes read access');
select public.fk_join(:'cid');
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
select fk_test.ok((select count(*)=0 from public.fk_reports),'owner cannot read others reports');
select fk_test.ok((select count(*)=2 from public.fk_profiles),'opt-in profile discoverable');
select fk_test.ok(fk_test.rejected(format('select public.fk_leave(%L)',:'cid')),'owner cannot orphan group');
select public.fk_delete_post(:'bpid');
select fk_test.ok((select count(*)=1 from public.fk_posts),'owner can moderate post');
select public.fk_ban(:'cid','22222222-2222-4222-8222-222222222222');
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',true);
select fk_test.ok((select count(*)=0 from public.fk_posts),'banned member cannot read');
select public.fk_leave(:'cid');
select fk_test.ok(fk_test.denied(format('select public.fk_join(%L)',:'cid')),'leaving cannot erase ban');
select fk_test.ok(fk_test.denied(format('select public.fk_ban(%L,''11111111-1111-4111-8111-111111111111'')',:'cid')),'member cannot ban owner');
select public.fk_delete_community(:'cid');
select fk_test.ok((select count(*)=1 from public.fk_communities),'nonowner cannot delete group');
select public.fk_delete_profile();
select fk_test.ok((select count(*)=0 from public.fk_profiles),'own profile deletion');
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
select fk_test.ok(fk_test.rejected('select public.fk_save_profile('''','''','''',false)'),'empty profile rejected');
select fk_test.ok(fk_test.rejected('select public.fk_create_community(''X'','''')'),'invalid community name rejected');
select fk_test.ok(fk_test.rejected('select public.fk_save_profile(repeat(''X'',61),'''','''',false)'),'oversized profile rejected');
select public.fk_delete_community(:'cid');
select fk_test.ok((select count(*)=0 from public.fk_posts),'group deletion cleans posts');
select fk_test.ok((select count(*)=0 from public.fk_memberships),'group deletion cleans memberships');
reset role;
update folkoop_private.pilots set enabled=false where user_id='11111111-1111-4111-8111-111111111111';
set local role authenticated;
select fk_test.ok((select count(*)=0 from public.fk_profiles),'pilot revocation immediately hides rows');
select fk_test.ok(fk_test.denied('select public.fk_save_profile(''Alice'','''','''',true)'),'pilot revocation blocks writes');
reset role;
rollback;
