/* Editorial copy. Planned activities are distinguished from shipped features. */
globalThis.SverinavAboutCopy = {
ru:{
by:'Кто делает проект',role:'Инициатор и ответственный за проект',why:'Зачем нужен Sverinav?',history:'Когда появился проект?',created:'Репозиторий кода создан',faq:'Частые вопросы',
intro:'Sverinav — независимый цифровой гражданский проект. Он помогает находить нужные государственные и муниципальные сервисы Швеции и экономить время при решении повседневных вопросов.',
purpose:'Начинай со своего вопроса, а не с поиска нужного ведомства. Sverinav объединяет короткую повседневную сводку и путь к официальному источнику. Мы планируем короткие пошаговые задания: решать местные проблемы, участвовать в обсуждении общих вопросов и помогать соседям. Игровые задания и награды ещё не запущены.',
bio:'Павел Чупрунов занимается гражданскими инициативами. На MittSkifte опубликована его кампания за введение ночных остановок общественного транспорта по запросу пассажиров в Гётеборге.',
contactNote:'Почта или Telegram откроются отдельно. Ты сам отправляешь сообщение; текст обращения и геопозиция из Sverinav не добавляются. Не присылай personnummer, пароли и чувствительные документы. Это не экстренная служба.',
dateNote:'Идея проекта возникла в 2021 году — по словам автора. Репозиторий кода создан 21 сентября 2026 года. Первый пилотный регион — Гётеборг.',
questions:[
['Это платно?','Sverinav бесплатен для жителей. Сохранять его бесплатным — принцип проекта. В текущем пилоте не нужен аккаунт. Внешние сервисы, например билеты, имеют собственные условия и стоимость.'],
['Что уже работает, а что пока в планах?','Подключены прогноз и предупреждения SMHI по лену, документы Riksdagen, открытые обсуждения планов Гётеборга и проверка ответственного за дорогу через NVDB. Транспорт и вода пока представлены ссылками, а не встроенными отправлениями, билетами или статусами отключений.'],
['Зачем мне документы Риксдага?','Они помогают проверить национальные предложения и решения: например, по школе, транспорту, экологии или государственным расходам. Сейчас доступны название, тип, даты и оригинал. Предложение или доклад комитета — не обязательно действующий закон; персональное объяснение последствий ещё не реализовано.'],
['Может ли обычный житель участвовать в обсуждении планов города?','Да. Во время открытого samråd или granskning можно прочитать проект и оставить замечания по инструкции Göteborgs Stad. Открой карточку, проверь срок, изложи конкретное замечание и отправь его через официальный канал. Это не голосование и не гарантия принятия предложения.'],
['Какие территории охватывает приложение?','Прогноз выбирается для одного из районов Гётеборга. Предупреждения SMHI относятся к лену Västra Götaland, а список планов — ко всему Гётеборгу. Выбор погоды не меняет остальные разделы. Персональные подписки пока в планах.'],
['Sverinav отправляет моё обращение?','Нет. Sverinav помогает определить ответственного за дорогу, подготовить описание и открыть официальный сервис. Ты проверяешь сведения и отправляешь обращение сам. GPS относится к месту телефона, а поле адреса пока служит примечанием.'],
['Можно показать здесь билет?','Нет. Sverinav направляет в официальный сервис Västtrafik, где можно посмотреть виды билетов, цены, купить и открыть действительный билет. Само приложение не продаёт билеты и не подтверждает оплату.'],
['Будут ли короткие задания и игровой прогресс?','Планируем добровольные задания с ясной целью, несколькими шагами и понятным результатом: например, разобраться с дорожной проблемой или подготовить замечание к городскому плану. Выполненный шаг не означает, что город уже исправил проблему. Баллы, награды и задания от соседей пока не доступны.'],
['Как проект будет финансироваться?','Модель ещё не выбрана. Рассматриваются поддержка проекта и платные инструменты для организаций при бесплатном пользовании для жителей. Помощь за баллы и партнёрские награды — отдельная идея, а не обещанный заработок. Правила, безопасность и возможные выплаты нужно проработать до запуска.'],
['Данные могут быть ошибочными или устаревшими?','Да. Источник может не отвечать, сведения — измениться, а код — содержать ошибки. Проверяй время, территорию действия и оригинал перед действием. Сбой проверки не означает, что всё спокойно.'],
['Что будет дальше?','Точные подписи, избранные остановки, значимые изменения, сохранённые даты и ручной выбор места дорожной проблемы. Пошаговые гражданские задания — новое направление разработки. Подписки, игровые баллы, награды и помощь соседям пока не запущены.']
]},
sv:{
by:'Personen bakom',role:'Initiativtagare och projektansvarig',why:'Varför finns Sverinav?',history:'När startade projektet?',created:'Kodarkivet skapades',faq:'Vanliga frågor',
intro:'Sverinav är ett oberoende digitalt samhällsprojekt. Det hjälper invånare att hitta rätt bland Sveriges statliga och kommunala tjänster och spara tid i vardagsärenden.',
purpose:'Börja med din fråga, inte med namnet på rätt myndighet. Sverinav samlar en kort vardagsöversikt och vägen till originalkällan. Vi planerar korta stegvisa uppdrag för lokala problem, samhällsfrågor och grannhjälp. Speluppdrag och belöningar är ännu inte lanserade.',
bio:'Pavel Chuprunov arbetar med medborgarinitiativ. På MittSkifte finns hans kampanj för nattstopp på begäran i Göteborgs kollektivtrafik.',
contactNote:'E-post eller Telegram öppnas separat. Du skickar själv; Sverinav lägger inte till ärendetext eller position. Skicka inte personnummer, lösenord eller känsliga dokument. Ingen akutkanal.',
dateNote:'Enligt initiativtagaren uppstod idén 2021. Kodarkivet skapades den 21 september 2026. Första pilotområdet är Göteborg.',
questions:[
['Kostar det något?','Sverinav är gratis för invånare. Att fortsätta vara gratis är en princip för projektet. Piloten kräver inget konto. Externa tjänster, exempelvis biljetter, har egna villkor och avgifter.'],
['Vad fungerar redan och vad är planerat?','SMHI-prognoser och länsvarningar, dokument från riksdagen, öppna Göteborgsplaner och väghållarkontroll via NVDB är anslutna. Resor och vatten är än så länge officiella länkar, inte inbyggda avgångar, biljetter eller avbrottsstatus.'],
['Varför läsa dokument från riksdagen?','De hjälper dig att kontrollera nationella förslag och beslut om exempelvis skola, trafik, miljö och statens utgifter. Nu visas titel, typ, datum och original. Ett förslag eller betänkande är inte nödvändigtvis en gällande lag; personlig konsekvensförklaring saknas ännu.'],
['Kan en vanlig invånare lämna synpunkter på stadens planer?','Ja. Under öppet samråd eller granskning kan du läsa förslaget och följa Göteborgs Stads instruktion. Öppna planen, kontrollera sista dag, skriv en konkret synpunkt och använd den officiella kanalen. Det är inte en omröstning eller garanti för att förslaget antas.'],
['Vilka områden täcker appen?','Prognosen gäller ett valt område i Göteborg. SMHI-varningarna gäller Västra Götalands län och planlistan hela Göteborg. Vädervalet filtrerar inte de andra delarna. Personliga bevakningar är planerade.'],
['Skickar Sverinav min felanmälan?','Nej. Sverinav hjälper dig att hitta väghållaren, förbereda en beskrivning och öppna rätt officiell tjänst. Du granskar och skickar själv. GPS gäller telefonens plats; adressfältet är än så länge en anteckning.'],
['Kan jag visa en biljett här?','Nej. Sverinav leder till Västtrafiks officiella tjänst för biljettyper, priser, köp och giltig biljett. Sverinav säljer inte biljetter och kontrollerar inte betalningar.'],
['Kommer det korta uppdrag och spelbaserade framsteg?','Vi planerar frivilliga uppdrag med ett mål, några steg och ett tydligt resultat: exempelvis undersöka ett vägfel eller förbereda en synpunkt på en plan. Ett slutfört steg betyder inte att kommunen löst problemet. Poäng, belöningar och grannuppdrag finns inte ännu.'],
['Hur ska projektet finansieras?','Modellen är inte beslutad. Stöd och betalda verktyg för organisationer övervägs, medan invånarnas användning förblir gratis. Hjälp mot poäng och partnerbelöningar är separata idéer, inte utlovad inkomst. Regler, säkerhet och ersättningar måste utredas före lansering.'],
['Kan informationen vara fel eller gammal?','Ja. Källor kan vara otillgängliga, uppgifter kan ändras och kod kan ha fel. Kontrollera tid, geografisk omfattning och originalkälla innan du agerar. En misslyckad kontroll betyder inte att allt är lugnt.'],
['Vad händer härnäst?','Tydligare etiketter, sparade hållplatser, relevanta förändringar, sparade datum och manuell plats för vägfel. Stegvisa samhällsuppdrag är en ny utvecklingsriktning. Bevakningar, spelpoäng, belöningar och grannhjälp är inte lanserade.']
]},
en:{
by:'Who is behind it',role:'Project initiator and maintainer',why:'Why does Sverinav exist?',history:'When did it start?',created:'Code repository created',faq:'Common questions',
intro:'Sverinav is an independent digital civic project. It helps residents find Swedish national and municipal services and save time on everyday public-service tasks.',
purpose:'Start with your question, not the name of the right authority. Sverinav combines a short daily overview with a path to official sources. We plan short step-by-step activities for local problems, public issues and helping neighbours. Game-based activities and rewards have not launched.',
bio:'Pavel Chuprunov develops civic initiatives. MittSkifte hosts his campaign for request-based night stops on Gothenburg public transport.',
contactNote:'Email or Telegram opens separately. You send the message yourself; Sverinav adds no report text or location. Do not send identity numbers, passwords or sensitive documents. Not an emergency channel.',
dateNote:'According to the initiator, the idea arose in 2021. The code repository was created on 21 September 2026. Gothenburg is the first pilot area.',
questions:[
['Does it cost anything?','Sverinav is free for residents. Keeping it free is a project principle. The pilot needs no account. External services, including tickets, have their own terms and charges.'],
['What works and what is planned?','SMHI forecasts and county warnings, Riksdag documents, open Gothenburg consultations and NVDB road-holder checks are connected. Travel and water are official links, not integrated departures, tickets or interruption status.'],
['Why read Riksdag documents?','They help you verify national proposals and decisions on schools, transport, the environment and public spending. Currently you see titles, types, dates and originals. A proposal or committee report is not necessarily a law in force; personalised impact explanations are not yet available.'],
['Can an ordinary resident comment on city plans?','Yes. During an open consultation or review, follow the City of Gothenburg’s instructions. Open the plan, check the deadline, write a specific comment and use the official channel. This is not a vote or a guarantee your proposal will be adopted.'],
['Which places does the app cover?','The forecast covers a chosen Gothenburg area. SMHI warnings cover Västra Götaland County and the plan list covers Gothenburg city. Choosing a weather area does not filter other sections. Personal watches are planned.'],
['Does Sverinav submit my report?','No. Sverinav helps identify the road holder, prepare a description and open the official service. You review and submit it yourself. GPS uses the phone’s location; the address field is currently a note.'],
['Can I display a ticket here?','No. Sverinav links to Västtrafik’s official service to check ticket types and prices, buy and display a valid ticket. Sverinav does not sell tickets or verify payment.'],
['Will there be short activities and game-like progress?','We plan optional activities with a goal, a few steps and a clear outcome: for example, investigating a road problem or preparing a comment on a plan. Completing a step does not mean the city fixed the problem. Points, rewards and neighbour tasks are not available yet.'],
['How will the project be funded?','The model is undecided. Support and paid tools for organisations are being considered while use by residents remains free. Help-for-points and partner rewards are separate ideas, not promised earnings. Rules, safety and compensation require review before launch.'],
['Can information be wrong or outdated?','Yes. Sources can be unavailable, information can change and code can contain errors. Check the time, geographic scope and original before acting. A failed check does not mean everything is fine.'],
['What comes next?','Clearer labels, saved stops, relevant changes, saved dates and manual road-problem location. Step-by-step civic activities are a new direction. Watches, game points, rewards and neighbour tasks are not launched.']
]},
uk:{
by:'Хто робить проєкт',role:'Ініціатор і відповідальний за проєкт',why:'Навіщо потрібен Sverinav?',history:'Коли з’явився проєкт?',created:'Репозиторій коду створено',faq:'Часті питання',
intro:'Sverinav — незалежний цифровий громадянський проєкт. Він допомагає знаходити державні та муніципальні сервіси Швеції й заощаджувати час у повсякденних справах.',
purpose:'Починайте зі свого питання, а не з пошуку відомства. Sverinav поєднує щоденний огляд і шлях до офіційного джерела. Плануємо короткі покрокові завдання для місцевих проблем, суспільних питань і допомоги сусідам. Ігрові завдання й нагороди ще не запущено.',
bio:'Павло Чупрунов займається громадянськими ініціативами. На MittSkifte опубліковано його кампанію за нічні зупинки громадського транспорту на прохання пасажирів у Гетеборзі.',
contactNote:'Пошта або Telegram відкриються окремо. Повідомлення надсилаєте ви; текст звернення й геопозиція не додаються. Не надсилайте personnummer, паролі та чутливі документи. Це не екстрена служба.',
dateNote:'За словами ініціатора, ідея виникла 2021 року. Репозиторій створено 21 вересня 2026 року. Перший пілот — Гетеборг.',
questions:[
['Це платно?','Sverinav безплатний для жителів. Зберігати його безплатним — принцип проєкту. Пілот не потребує акаунта. Зовнішні сервіси, наприклад квитки, мають власні умови й вартість.'],
['Що вже працює?','Прогноз і попередження SMHI, документи Riksdagen, відкриті обговорення планів Гетеборга та перевірка відповідального за дорогу через NVDB. Транспорт і вода — посилання, не вбудовані відправлення, квитки чи статуси відключень.'],
['Навіщо документи Риксдагу?','Щоб перевірити національні пропозиції й рішення щодо освіти, транспорту, довкілля та державних витрат. Показано назву, тип, дати й оригінал. Пропозиція чи доповідь комітету не обов’язково є чинним законом; персональне пояснення наслідків ще не реалізоване.'],
['Чи може звичайний житель коментувати плани міста?','Так. Під час відкритого samråd або granskning прочитайте проєкт, перевірте строк, напишіть конкретне зауваження та надішліть за інструкцією Göteborgs Stad. Це не голосування й не гарантія прийняття пропозиції.'],
['Які території охоплює застосунок?','Прогноз стосується обраного району Гетеборга, попередження SMHI — лену Västra Götaland, а плани — всього міста. Вибір погоди не змінює інші розділи. Особисті підписки заплановано.'],
['Sverinav надсилає звернення?','Ні. Допомагає визначити відповідального за дорогу, підготувати опис і відкрити офіційний сервіс. Ви перевіряєте й надсилаєте самі. GPS стосується телефона; адреса поки є приміткою.'],
['Можна показати тут квиток?','Ні. Sverinav веде до офіційного сервісу Västtrafik для видів квитків, цін, купівлі й показу чинного квитка. Сам не продає квитки й не перевіряє оплату.'],
['Чи будуть короткі завдання та ігровий прогрес?','Плануємо добровільні завдання з метою, кількома кроками й результатом: розібратися з проблемою дороги або підготувати зауваження до плану. Виконаний крок не означає, що місто усунуло проблему. Балів, нагород і завдань від сусідів ще немає.'],
['Як фінансуватиметься проєкт?','Модель ще не обрана. Розглядаються підтримка та платні інструменти для організацій при безплатному користуванні жителями. Допомога за бали й партнерські нагороди — ідеї, не обіцяний заробіток. Перед запуском потрібні правила й перевірка безпеки та виплат.'],
['Дані можуть бути помилковими чи застарілими?','Так. Джерела можуть не відповідати, відомості — змінюватися, а код — містити помилки. Перевіряйте час, територію й оригінал. Збій перевірки не означає, що все спокійно.'],
['Що далі?','Точні підписи, обрані зупинки, значущі зміни, дати й ручний вибір місця проблеми. Покрокові громадянські завдання — новий напрям. Підписки, бали, нагороди й допомога сусідам ще не запущені.']
]},
fi:{
by:'Hankkeen tekijä',role:'Hankkeen alullepanija ja ylläpitäjä',why:'Miksi Sverinav on olemassa?',history:'Milloin hanke alkoi?',created:'Koodivarasto luotu',faq:'Usein kysyttyä',
intro:'Sverinav on itsenäinen digitaalinen kansalaisprojekti. Se auttaa löytämään Ruotsin valtion ja kuntien palvelut ja säästämään aikaa arjen asioinnissa.',
purpose:'Aloita kysymyksestäsi, älä viranomaisen nimestä. Sverinav yhdistää lyhyen päiväkatsauksen ja viralliset lähteet. Suunnittelemme vaiheittaisia tehtäviä paikallisiin ongelmiin, yhteiskunnan kysymyksiin ja naapuriapuun. Pelitehtäviä tai palkintoja ei ole vielä julkaistu.',
bio:'Pavel Chuprunov tekee kansalaisaloitteita. MittSkiftessä on hänen kampanjansa pyynnöstä tehtävistä yöpysähdyksistä Göteborgin joukkoliikenteessä.',
contactNote:'Sähköposti tai Telegram avautuu erikseen. Lähetät viestin itse; ilmoitustekstiä tai sijaintia ei lisätä. Älä lähetä henkilötunnuksia, salasanoja tai arkaluonteisia asiakirjoja. Ei hätäpalvelu.',
dateNote:'Aloitteentekijän mukaan idea syntyi vuonna 2021. Koodivarasto luotiin 21. syyskuuta 2026. Ensimmäinen pilottialue on Göteborg.',
questions:[
['Maksaako käyttö?','Sverinav on asukkaille maksuton. Maksuttomuuden säilyttäminen on hankkeen periaate. Pilotti ei vaadi tiliä. Ulkoisilla palveluilla, kuten lipuilla, on omat ehtonsa ja hintansa.'],
['Mikä toimii jo?','SMHI:n ennuste ja läänin varoitukset, valtiopäivien asiakirjat, Göteborgin kuulemiset ja NVDB-tienpitäjätarkistus. Liikenne ja vesi ovat virallisia linkkejä, eivät lähtö-, lippu- tai katkotietointegraatioita.'],
['Miksi lukea valtiopäivien asiakirjoja?','Niistä voi tarkistaa kansallisia ehdotuksia ja päätöksiä koulutuksesta, liikenteestä, ympäristöstä ja valtion menoista. Näytetään otsikko, tyyppi, päivät ja alkuperäinen. Ehdotus tai mietintö ei välttämättä ole voimassa oleva laki; henkilökohtaisia vaikutuksia ei vielä selitetä.'],
['Voiko tavallinen asukas kommentoida kaupungin suunnitelmia?','Kyllä. Avoimen samrådin tai granskningin aikana voit lukea suunnitelman, tarkistaa määräajan ja lähettää konkreettisen mielipiteen Göteborgin kaupungin ohjeiden mukaan. Kyse ei ole äänestyksestä tai hyväksymisen takuusta.'],
['Mitä alueita sovellus kattaa?','Ennuste koskee valittua Göteborgin aluetta, SMHI-varoitukset Västra Götalandin lääniä ja suunnitelmat koko Göteborgia. Säävalinta ei suodata muita osioita. Henkilökohtainen seuranta on suunnitteilla.'],
['Lähettääkö Sverinav vikailmoituksen?','Ei. Se auttaa löytämään tienpitäjän, laatimaan kuvauksen ja avaamaan virallisen palvelun. Tarkistat ja lähetät itse. GPS käyttää puhelimen sijaintia; osoitekenttä on muistiinpano.'],
['Voinko näyttää lipun täällä?','Et. Sverinav ohjaa Västtrafikin viralliseen palveluun katsomaan lipputyyppejä ja hintoja sekä ostamaan ja näyttämään lipun. Sverinav ei myy lippuja eikä vahvista maksua.'],
['Tuleeko lyhyitä tehtäviä ja pelillistä edistymistä?','Suunnittelemme vapaaehtoisia tehtäviä, joissa on tavoite, muutama vaihe ja tulos: esimerkiksi tieongelman selvitys tai mielipiteen valmistelu. Suoritettu vaihe ei tarkoita kaupungin korjanneen ongelman. Pisteitä, palkintoja tai naapuritehtäviä ei vielä ole.'],
['Miten hanke rahoitetaan?','Mallia ei ole päätetty. Tukea ja organisaatioiden maksullisia työkaluja harkitaan asukkaiden käytön pysyessä maksuttomana. Pisteapu ja kumppanipalkinnot ovat ideoita, eivät luvattuja ansioita. Säännöt, turvallisuus ja korvaukset selvitetään ennen julkaisua.'],
['Voivatko tiedot olla vääriä tai vanhoja?','Kyllä. Lähteet voivat olla poissa käytöstä, tiedot muuttua ja koodissa olla virheitä. Tarkista aika, alue ja alkuperäinen. Epäonnistunut tarkistus ei tarkoita, että kaikki on kunnossa.'],
['Mitä seuraavaksi?','Selkeät tekstit, omat pysäkit, olennaiset muutokset, päivät ja tievian paikan valinta käsin. Vaiheittaiset kansalaistehtävät ovat uusi suunta. Seurantoja, pisteitä, palkintoja tai naapuriapua ei vielä ole.']
]},
es:{
by:'Quién está detrás',role:'Impulsor y responsable del proyecto',why:'¿Por qué existe Sverinav?',history:'¿Cuándo comenzó?',created:'Repositorio de código creado',faq:'Preguntas frecuentes',
intro:'Sverinav es un proyecto ciudadano digital e independiente. Ayuda a encontrar servicios estatales y municipales de Suecia y ahorrar tiempo en gestiones cotidianas.',
purpose:'Empieza por tu pregunta, no por el nombre de la autoridad. Sverinav combina un resumen diario y fuentes oficiales. Planeamos actividades breves por pasos para problemas locales, asuntos públicos y ayuda vecinal. Las actividades de juego y recompensas aún no están disponibles.',
bio:'Pavel Chuprunov impulsa iniciativas ciudadanas. MittSkifte publica su campaña para introducir paradas nocturnas a petición en el transporte público de Gotemburgo.',
contactNote:'El correo o Telegram se abre por separado. Tú envías el mensaje; no se añade texto del aviso ni ubicación. No envíes números personales, contraseñas ni documentos sensibles. No es un canal de emergencias.',
dateNote:'Según el impulsor, la idea nació en 2021. El repositorio se creó el 21 de septiembre de 2026. El primer piloto es Gotemburgo.',
questions:[
['¿Tiene coste?','Sverinav es gratuito para residentes. Mantenerlo gratuito es un principio del proyecto. El piloto no exige cuenta. Los servicios externos, como billetes, tienen condiciones y tarifas propias.'],
['¿Qué funciona ya?','Pronóstico y avisos provinciales de SMHI, documentos del Parlamento, consultas de Gotemburgo y responsables de vías mediante NVDB. Transporte y agua son enlaces oficiales, no salidas, billetes ni estados de cortes integrados.'],
['¿Para qué sirven los documentos del Parlamento?','Permiten verificar propuestas y decisiones nacionales sobre educación, transporte, medio ambiente y gasto público. Se muestra título, tipo, fechas y original. Una propuesta o informe de comisión no es necesariamente una ley vigente; aún no hay explicaciones de impacto personal.'],
['¿Puede un residente comentar los planes urbanos?','Sí. Durante un samråd o granskning abierto puedes leer el plan, comprobar el plazo y enviar un comentario concreto según las instrucciones del Ayuntamiento. No es una votación ni garantía de aprobación.'],
['¿Qué territorios cubre la aplicación?','El pronóstico cubre una zona de Gotemburgo, los avisos SMHI la provincia de Västra Götaland y los planes toda la ciudad. Elegir zona meteorológica no filtra otras secciones. El seguimiento personal está previsto.'],
['¿Sverinav envía mi aviso?','No. Ayuda a identificar al responsable de la vía, preparar una descripción y abrir el servicio oficial. Tú revisas y envías. El GPS usa la ubicación del teléfono; la dirección es una nota.'],
['¿Puedo mostrar aquí un billete?','No. Sverinav dirige al servicio oficial de Västtrafik para ver tipos y precios, comprar y mostrar un billete válido. No vende billetes ni verifica pagos.'],
['¿Habrá actividades cortas y progreso de juego?','Planeamos tareas voluntarias con un objetivo, algunos pasos y un resultado, como investigar un problema vial o preparar un comentario sobre un plan. Completar un paso no significa que el Ayuntamiento haya resuelto el problema. Puntos, recompensas y tareas vecinales aún no existen.'],
['¿Cómo se financiará el proyecto?','No se ha elegido el modelo. Se consideran apoyo y herramientas de pago para organizaciones, manteniendo gratuito el uso residencial. Ayuda por puntos y recompensas son ideas, no ingresos prometidos. Reglas, seguridad y pagos requieren revisión previa.'],
['¿Puede haber datos incorrectos o antiguos?','Sí. Las fuentes pueden fallar, los datos cambiar y el código tener errores. Comprueba la hora, el alcance y el original. Un fallo no significa que todo esté bien.'],
['¿Qué sigue?','Etiquetas claras, paradas guardadas, cambios relevantes, fechas y ubicación manual de problemas viales. Las actividades ciudadanas por pasos son una nueva línea. Seguimientos, puntos, premios y tareas vecinales aún no están disponibles.']
]},
bs:{
by:'Ko stoji iza projekta',role:'Pokretač i odgovorna osoba projekta',why:'Zašto postoji Sverinav?',history:'Kada je projekat počeo?',created:'Repozitorij koda je kreiran',faq:'Česta pitanja',
intro:'Sverinav je nezavisni digitalni građanski projekat. Pomaže stanovnicima da pronađu državne i općinske usluge Švedske i uštede vrijeme u svakodnevnim poslovima.',
purpose:'Počni od svog pitanja, ne naziva institucije. Sverinav spaja dnevni pregled i službene izvore. Planiramo kratke zadatke korak po korak za lokalne probleme, javna pitanja i pomoć komšijama. Igrivi zadaci i nagrade još nisu pokrenuti.',
bio:'Pavel Chuprunov pokreće građanske inicijative. Na MittSkifte je njegova kampanja za noćna zaustavljanja javnog prijevoza na zahtjev u Göteborgu.',
contactNote:'E-pošta ili Telegram otvara se zasebno. Sam šalješ poruku; tekst prijave i lokacija se ne dodaju. Ne šalji personnummer, lozinke ili osjetljive dokumente. Nije hitna služba.',
dateNote:'Prema inicijatoru, ideja je nastala 2021. Repozitorij je kreiran 21. septembra 2026. Prvi pilot je Göteborg.',
questions:[
['Da li se plaća?','Sverinav je besplatan za stanovnike. Očuvanje besplatnog pristupa je princip projekta. Pilot ne zahtijeva račun. Vanjske usluge, poput karata, imaju svoje uslove i cijene.'],
['Šta već radi?','SMHI prognoza i okružna upozorenja, parlamentarni dokumenti, konsultacije Göteborga i provjera upravljača ceste kroz NVDB. Prijevoz i voda su službeni linkovi, ne ugrađeni polasci, karte ili status prekida.'],
['Zašto čitati dokumente parlamenta?','Za provjeru nacionalnih prijedloga i odluka o obrazovanju, prijevozu, okolišu i javnoj potrošnji. Prikazujemo naslov, vrstu, datume i original. Prijedlog ili izvještaj odbora nije nužno važeći zakon; lične posljedice još se ne objašnjavaju.'],
['Može li običan stanovnik komentarisati gradske planove?','Da. Tokom otvorenog samråd ili granskning postupka pročitaj plan, provjeri rok i pošalji konkretan komentar prema uputama Grada Göteborga. To nije glasanje ni garancija prihvatanja.'],
['Koja područja aplikacija pokriva?','Prognoza pokriva odabrano područje Göteborga, SMHI upozorenja okrug Västra Götaland, a planovi cijeli Göteborg. Vremenski izbor ne filtrira druge dijelove. Lična praćenja su planirana.'],
['Šalje li Sverinav moju prijavu?','Ne. Pomaže pronaći upravljača ceste, pripremiti opis i otvoriti službenu uslugu. Sam provjeravaš i šalješ. GPS koristi položaj telefona; adresa je zasad bilješka.'],
['Mogu li ovdje pokazati kartu?','Ne. Sverinav vodi na službenu uslugu Västtrafika za vrste i cijene karata, kupovinu i prikaz važeće karte. Ne prodaje karte niti provjerava uplatu.'],
['Hoće li biti kratkih zadataka i napretka kroz igru?','Planiramo dobrovoljne zadatke s ciljem, nekoliko koraka i rezultatom, poput provjere problema na cesti ili pripreme komentara. Završen korak ne znači da je grad popravio problem. Bodovi, nagrade i zadaci komšija još nisu dostupni.'],
['Kako će se projekat finansirati?','Model nije izabran. Razmatraju se podrška i plaćeni alati za organizacije uz besplatnu upotrebu stanovnika. Pomoć za bodove i nagrade su ideje, ne obećana zarada. Prije pokretanja treba razraditi pravila, sigurnost i isplate.'],
['Mogu li podaci biti pogrešni ili zastarjeli?','Da. Izvori mogu biti nedostupni, podaci se mijenjati, a kod sadržavati greške. Provjeri vrijeme, područje i original. Neuspjela provjera ne znači da je sve u redu.'],
['Šta slijedi?','Jasne oznake, sačuvana stajališta, bitne promjene, datumi i ručni izbor mjesta problema. Građanski zadaci korak po korak su novi pravac. Praćenja, bodovi, nagrade i komšijski zadaci još nisu pokrenuti.']
]},
ar:{
by:'من وراء المشروع',role:'صاحب المبادرة والمسؤول عن المشروع',why:'لماذا يوجد Sverinav؟',history:'متى بدأ المشروع؟',created:'أُنشئ مستودع الكود في',faq:'أسئلة شائعة',
intro:'Sverinav مشروع مدني رقمي مستقل. يساعد السكان على إيجاد الخدمات الحكومية والبلدية في السويد وتوفير الوقت في شؤونهم اليومية.',
purpose:'ابدأ بسؤالك لا باسم الجهة. يجمع Sverinav ملخصاً يومياً وطريقاً إلى المصادر الرسمية. نخطط لمهام قصيرة بخطوات واضحة للمشكلات المحلية والشؤون العامة ومساعدة الجيران. المهام والألعاب والمكافآت لم تُطلق بعد.',
bio:'يعمل Pavel Chuprunov على مبادرات مدنية. تنشر MittSkifte حملته لإتاحة توقف النقل العام ليلاً عند طلب الركاب في غوتنبرغ.',
contactNote:'يفتح البريد أو Telegram منفصلاً. أنت ترسل الرسالة؛ لا يُضاف نص البلاغ أو الموقع تلقائياً. لا ترسل الرقم الشخصي أو كلمات المرور أو وثائق حساسة. ليست خدمة طوارئ.',
dateNote:'وفقاً لصاحب المبادرة، ظهرت الفكرة عام 2021. أُنشئ مستودع الكود في 21 سبتمبر 2026. المنطقة التجريبية الأولى غوتنبرغ.',
questions:[
['هل الاستخدام مدفوع؟','Sverinav مجاني للسكان. إبقاؤه مجانياً مبدأ للمشروع. النسخة التجريبية لا تتطلب حساباً. للخدمات الخارجية مثل التذاكر شروطها ورسومها.'],
['ما الذي يعمل فعلاً؟','توقعات SMHI وتحذيرات المقاطعة ووثائق البرلمان وخطط غوتنبرغ المفتوحة وفحص مسؤول الطريق عبر NVDB. النقل والمياه روابط رسمية وليست مواعيد أو تذاكر أو حالات انقطاع مدمجة.'],
['ما فائدة وثائق البرلمان؟','للتحقق من المقترحات والقرارات الوطنية بشأن التعليم والنقل والبيئة والإنفاق العام. يعرض Sverinav العنوان والنوع والتواريخ والأصل. المقترح أو تقرير اللجنة ليس بالضرورة قانوناً سارياً؛ شرح الأثر الشخصي لم يُنفذ بعد.'],
['هل يستطيع المقيم العادي التعليق على خطط المدينة؟','نعم. خلال samråd أو granskning مفتوح، اقرأ الخطة وتحقق من الموعد وأرسل ملاحظة محددة وفق تعليمات بلدية غوتنبرغ. هذا ليس تصويتاً أو ضماناً لقبول الاقتراح.'],
['ما المناطق التي يغطيها التطبيق؟','التوقعات لمنطقة مختارة في غوتنبرغ، وتحذيرات SMHI لمقاطعة Västra Götaland، والخطط للمدينة كلها. اختيار منطقة الطقس لا يغير الأقسام الأخرى. المتابعات الشخصية مخططة.'],
['هل يرسل Sverinav بلاغي؟','لا. يساعد على تحديد مسؤول الطريق وإعداد وصف وفتح الخدمة الرسمية. تراجع وترسل بنفسك. يستخدم GPS موقع الهاتف؛ حقل العنوان ملاحظة حالياً.'],
['هل يمكنني عرض تذكرة هنا؟','لا. يوجه Sverinav إلى خدمة Västtrafik الرسمية لمعرفة أنواع التذاكر وأسعارها وشرائها وعرض التذكرة الصالحة. لا يبيع التذاكر ولا يؤكد الدفع.'],
['هل ستكون هناك مهام قصيرة وتقدم شبيه بالألعاب؟','نخطط لمهام اختيارية بهدف وخطوات ونتيجة، مثل فحص مشكلة طريق أو إعداد تعليق على خطة. إتمام خطوة لا يعني أن المدينة أصلحت المشكلة. النقاط والمكافآت ومهام الجيران غير متاحة بعد.'],
['كيف سيموّل المشروع؟','لم يُختَر النموذج بعد. يُدرس الدعم وأدوات مدفوعة للمنظمات مع بقاء استخدام السكان مجانياً. المساعدة مقابل نقاط ومكافآت الشركاء أفكار وليست دخلاً موعوداً. يجب مراجعة القواعد والسلامة والتعويض قبل الإطلاق.'],
['هل يمكن أن تكون البيانات خاطئة أو قديمة؟','نعم. قد تتعطل المصادر أو تتغير البيانات أو يحتوي الكود على أخطاء. تحقق من الوقت والنطاق والأصل قبل التصرف. فشل الفحص لا يعني أن كل شيء بخير.'],
['ما الخطوة التالية؟','عناوين أوضح ومحطات محفوظة وتغييرات مهمة ومواعيد واختيار مكان مشكلة الطريق يدوياً. المهام المدنية بخطوات اتجاه جديد. المتابعات والنقاط والمكافآت ومساعدة الجيران غير متاحة بعد.']
]},
fa:{
by:'چه کسی پشت پروژه است',role:'آغازگر و مسئول پروژه',why:'Sverinav برای چیست؟',history:'پروژه چه زمانی شروع شد؟',created:'مخزن کد ایجاد شد',faq:'پرسش‌های رایج',
intro:'Sverinav یک پروژه مستقل دیجیتال و مدنی است. به ساکنان کمک می‌کند خدمات دولتی و شهرداری سوئد را پیدا کنند و در امور روزمره وقت کمتری صرف کنند.',
purpose:'از پرسش خود شروع کنید، نه نام نهاد. Sverinav مرور روزانه و مسیر منابع رسمی را گرد هم می‌آورد. فعالیت‌های کوتاه مرحله‌ای برای مسائل محلی، عمومی و کمک به همسایگان برنامه‌ریزی شده‌اند. بازی‌ها و پاداش‌ها هنوز راه‌اندازی نشده‌اند.',
bio:'Pavel Chuprunov در زمینه ابتکارهای مدنی فعالیت می‌کند. MittSkifte کارزار او برای توقف شبانه حمل‌ونقل عمومی به درخواست مسافر در یوتبری را منتشر کرده است.',
contactNote:'ایمیل یا Telegram جداگانه باز می‌شود. خودتان پیام را می‌فرستید؛ متن گزارش و مکان اضافه نمی‌شود. شماره شخصی، رمز یا مدارک حساس نفرستید. این خدمت اضطراری نیست.',
dateNote:'به گفته آغازگر، ایده در سال ۲۰۲۱ شکل گرفت. مخزن کد در ۲۱ سپتامبر ۲۰۲۶ ایجاد شد. نخستین منطقه آزمایشی یوتبری است.',
questions:[
['آیا هزینه دارد؟','Sverinav برای ساکنان رایگان است. رایگان ماندن اصل پروژه است. نسخه آزمایشی حساب نمی‌خواهد. خدمات بیرونی مانند بلیت شرایط و هزینه خود را دارند.'],
['چه چیزهایی اکنون کار می‌کند؟','پیش‌بینی و هشدارهای استانی SMHI، اسناد پارلمان، طرح‌های باز یوتبری و بررسی مسئول راه با NVDB. حمل‌ونقل و آب پیوند رسمی هستند، نه زمان حرکت، بلیت یا وضعیت قطعی درون برنامه.'],
['اسناد پارلمان چه فایده‌ای دارند؟','برای بررسی پیشنهادها و تصمیم‌های ملی درباره مدرسه، حمل‌ونقل، محیط‌زیست و هزینه عمومی. اکنون عنوان، نوع، تاریخ و اصل نمایش داده می‌شود. پیشنهاد یا گزارش کمیته لزوماً قانون جاری نیست؛ توضیح اثر شخصی هنوز وجود ندارد.'],
['آیا ساکن عادی می‌تواند درباره طرح شهری نظر بدهد؟','بله. در samråd یا granskning باز، طرح و مهلت را بخوانید و نظر مشخصی طبق دستور شهرداری یوتبری بفرستید. این رأی‌گیری یا تضمین پذیرش پیشنهاد نیست.'],
['برنامه کدام مناطق را پوشش می‌دهد؟','پیش‌بینی برای منطقه انتخابی یوتبری، هشدار SMHI برای استان Västra Götaland و طرح‌ها برای کل شهر است. انتخاب هوا بخش‌های دیگر را فیلتر نمی‌کند. پیگیری شخصی در برنامه است.'],
['آیا Sverinav گزارش من را می‌فرستد؟','خیر. به شناسایی مسئول راه، تهیه شرح و باز کردن خدمت رسمی کمک می‌کند. خودتان بررسی و ارسال می‌کنید. GPS مکان تلفن است؛ نشانی فعلاً یادداشت است.'],
['می‌توانم اینجا بلیت نشان دهم؟','خیر. Sverinav به خدمت رسمی Västtrafik برای انواع و قیمت بلیت، خرید و نمایش بلیت معتبر راهنمایی می‌کند. بلیت نمی‌فروشد و پرداخت را تأیید نمی‌کند.'],
['آیا فعالیت کوتاه و پیشرفت بازی‌مانند خواهد بود؟','فعالیت اختیاری با هدف، چند مرحله و نتیجه برنامه‌ریزی می‌کنیم؛ مثلاً بررسی مشکل راه یا تهیه نظر درباره طرح. انجام مرحله به معنی حل شدن مشکل توسط شهر نیست. امتیاز، پاداش و کار همسایگی هنوز در دسترس نیست.'],
['پروژه چگونه تأمین مالی می‌شود؟','مدل انتخاب نشده. حمایت و ابزار پولی سازمان‌ها با حفظ استفاده رایگان ساکنان بررسی می‌شود. کمک در برابر امتیاز و پاداش شریک ایده است، نه درآمد وعده‌داده‌شده. قواعد، ایمنی و جبران مالی پیش از آغاز نیاز به بررسی دارند.'],
['ممکن است اطلاعات اشتباه یا قدیمی باشد؟','بله. منابع ممکن است قطع شوند، داده تغییر کند یا کد خطا داشته باشد. زمان، محدوده و اصل را پیش از اقدام بررسی کنید. شکست بررسی به معنی آرام بودن همه‌چیز نیست.'],
['قدم بعدی چیست؟','عنوان روشن، ایستگاه ذخیره‌شده، تغییر مرتبط، تاریخ و انتخاب دستی مکان مشکل راه. فعالیت مدنی مرحله‌ای مسیر تازه است. پیگیری، امتیاز، پاداش و کمک همسایگی هنوز راه‌اندازی نشده‌اند.']
]},
so:{
by:'Qofka mashruuca ka dambeeya',role:'Bilaabaha iyo masuulka mashruuca',why:'Maxaa Sverinav loo sameeyay?',history:'Goorma ayuu bilowday?',created:'Kaydka koodka waxaa la sameeyay',faq:'Su’aalaha caanka ah',
intro:'Sverinav waa mashruuc muwaadinimo dijitaal ah oo madax-bannaan. Wuxuu dadka ka caawiyaa helidda adeegyada dowladda iyo degmooyinka Sweden iyo badbaadinta waqtiga arrimaha maalinlaha ah.',
purpose:'Ka bilow su’aashaada, ma aha magaca hay’adda. Sverinav wuxuu isku daraa warbixin kooban iyo ilo rasmi ah. Waxaan qorshaynaynaa hawlo gaagaaban oo tallaabooyin leh oo arrimaha deegaanka, bulshada iyo caawinta deriska ah. Hawlaha ciyaarta iyo abaalmarinnadu weli ma bilaabmin.',
bio:'Pavel Chuprunov wuxuu ka shaqeeyaa dadaallo muwaadinimo. MittSkifte waxaa ku qoran ololihiisa joogsiyada habeenkii ee gaadiidka Göteborg marka rakaabku codsado.',
contactNote:'Email ama Telegram ayaa gooni u furmaya. Adiga ayaa dira; qoraalka warbixinta iyo goobta laguma daro. Ha dirin personnummer, furaha sirta ama dukumenti xasaasi ah. Ma aha adeeg degdeg ah.',
dateNote:'Sida uu sheegay bilaabaha, fikraddu waxay dhalatay 2021. Kaydka koodka waxaa la sameeyay 21 Sebtembar 2026. Tijaabada koowaad waa Göteborg.',
questions:[
['Lacag ma laga bixiyaa?','Sverinav waa bilaash dadka deggan. Inuu bilaash ahaado waa mabda’a mashruuca. Tijaabadu akoon uma baahna. Adeegyada dibadda sida tigidhadu waxay leeyihiin qiimo iyo shuruudo u gaar ah.'],
['Maxaa hadda shaqeeya?','Saadaasha iyo digniinaha gobolka ee SMHI, dukumentiyada baarlamaanka, qorshayaasha furan ee Göteborg iyo masuulka waddada ee NVDB. Gaadiidka iyo biyuhu waa xiriirro rasmi ah, ma aha bixitaanno, tigidh ama xaalad biyo-joojin oo gudaha ku jira.'],
['Maxay faa’iido leeyihiin dukumentiyada baarlamaanku?','Si loo hubiyo soo-jeedin iyo go’aan qaran oo ku saabsan iskuul, gaadiid, deegaan iyo kharashka dowladda. Hadda waxaa muuqda cinwaan, nooc, taariikh iyo asal. Soo-jeedin ama warbixin guddi mar walba ma aha sharci shaqaynaya; saameyn shaqsiyeed weli lama sharxo.'],
['Qof deggan ma ka dhiiban karaa fikrad qorshaha magaalada?','Haa. Inta samråd ama granskning furan yahay, akhri qorshaha, hubi waqtiga oo dir fikrad gaar ah sida Göteborgs Stad tilmaamay. Ma aha codbixin ama ballan in fikradda la aqbalayo.'],
['Aaggee app-ku daboolayaa?','Saadaashu waa aagga Göteborg ee la doortay; digniinaha SMHI waa gobolka Västra Götaland; qorshayaashuna waa magaalada oo dhan. Aagga cimiladu ma beddelo qaybaha kale. La socodka shakhsiga ah waa qorshe.'],
['Sverinav ma diraa warbixintayda?','Maya. Wuxuu kaa caawiyaa helidda masuulka waddada, diyaarinta sharaxaad iyo furidda adeegga rasmiga ah. Adiga ayaa hubiya oo dira. GPS waa goobta telefoonka; cinwaanku waa qoraal xusuus ah.'],
['Tigidh ma ku muujin karaa halkan?','Maya. Sverinav wuxuu kuu tilmaamaa adeegga rasmiga ah ee Västtrafik si aad u aragto noocyada iyo qiimaha tigidhada, u iibsato una muujiso tigidh sax ah. Ma iibiyo tigidh mana xaqiijiyo lacag.'],
['Hawlo kooban iyo horumar ciyaar ma jiri doonaan?','Waxaan qorshaynaynaa hawlo ikhtiyaari ah oo leh ujeeddo, tallaabooyin iyo natiijo: hubinta cilad waddo ama diyaarinta fikrad qorshe. Tallaabo dhammaatay micnaheedu ma aha in magaalada dhibaatada xallisay. Dhibco, abaalmarin iyo hawlo deris weli lama heli karo.'],
['Sidee mashruuca loo maalgelin doonaa?','Qaabka lama dooran. Taageero iyo qalab lacag ah oo ururrada loogu talagalay ayaa la tixgelinayaa iyadoo dadka deggan bilaash u isticmaalayaan. Caawin dhibco lagu helo iyo abaalmarin waa fikrado, ma aha dakhli la ballanqaaday. Xeerarka, badbaadada iyo lacagta waa in la hubiyaa ka hor bilowga.'],
['Xogtu ma khaldan kartaa ama duugoobi kartaa?','Haa. Iluhu way maqnaan karaan, xogtu way is beddeli kartaa, koodkuna wuu khaldami karaa. Hubi waqtiga, aagga iyo asalka. Hubin fashilantay micnaheedu ma aha in wax walba fiican yihiin.'],
['Maxaa xiga?','Erayo cad, joogsiyo la kaydiyo, isbeddello khuseeya, taariikho iyo goobta ciladda oo gacanta la doorto. Hawlaha muwaadinimo ee tallaabooyinka leh waa jiho cusub. La socod, dhibco, abaalmarin iyo hawlo deris weli ma shaqeeyaan.']
]},
ku:{
by:'Kesê li pişt projeyê',role:'Destpêker û berpirsiyarê projeyê',why:'Sverinav ji bo çi heye?',history:'Proje kengî dest pê kir?',created:'Depoya kodê hate afirandin',faq:'Pirsên gelemperî',
intro:'Sverinav projeyek dijîtal a hemwelatî ya serbixwe ye. Alîkariya niştecihan dike ku xizmetên dewlet û şaredariyên Swêdê bibînin û di karên rojane de demê biparêzin.',
purpose:'Bi pirsa xwe dest pê bike, ne bi navê saziyê. Sverinav kurteya rojane û çavkaniyên fermî dicivîne. Em karên kurt ên gav-bi-gav ji bo pirsgirêkên herêmê, mijarên giştî û alîkariya cîranan plan dikin. Karên lîstikê û xelat hîn nehatine destpêkirin.',
bio:'Pavel Chuprunov li ser destpêşxeriyên hemwelatî dixebite. Li MittSkifte kampanyaya wî ji bo rawestina şevê ya veguhastina giştî bi daxwaza rêwiyan li Göteborgê heye.',
contactNote:'E-name an Telegram cuda vedibe. Tu peyamê dişînî; nivîsa raporê û cih nayên zêdekirin. Personnummer, şîfre an belgeyên hestiyar neşîne. Ne xeta awarte ye.',
dateNote:'Li gor destpêker, fikir di 2021 de derket. Depoya kodê di 21 Îlona 2026 de hate afirandin. Pilota yekem Göteborg e.',
questions:[
['Bi pere ye?','Sverinav ji bo niştecihan belaş e. Belaş mayîn prensîba projeyê ye. Pilot hesab naxwaze. Xizmetên derve wek bilêt şert û bihayên xwe hene.'],
['Niha çi kar dike?','Pêşbîniya SMHI, hişyariyên herêmê, belgeyên parlamentoyê, planên vekirî yên Göteborgê û berpirsiyarê rê bi NVDB. Rêwîtî û av hîn girêdanên fermî ne, ne derketin, bilêt an rewşa birîna avê ya hundirîn.'],
['Belgeyên parlamentoyê ji bo çi ne?','Ji bo kontrola pêşniyar û biryarên neteweyî li ser dibistan, veguhastin, jîngeh û xerckirina giştî. Niha sernav, cure, dîrok û orîjînal hene. Pêşniyar an rapora komîteyê ne her tim qanûna derbasdar e; bandora kesane hîn nayê ravekirin.'],
['Niştecihek dikare li ser planên bajêr nerîn bide?','Erê. Di samråd an granskning a vekirî de planê bixwîne, dema dawî kontrol bike û nerîneke diyarkirî li gor rêberiya Göteborgs Stad bişîne. Ev ne dengdan an garantiya qebûlkirinê ye.'],
['App kîjan herêman digire?','Pêşbînî ji bo herêma hilbijartî ya Göteborgê ye; hişyariyên SMHI ji bo Västra Götaland û plan ji bo hemû bajêr in. Hilbijartina hewayê beşên din naguhere. Şopandina kesane di planê de ye.'],
['Sverinav rapora min dişîne?','Na. Alîkar e ku berpirsiyarê rê bibînî, ravekirinê amade bikî û xizmeta fermî vekî. Tu kontrol û şandinê dikî. GPS cihê telefonê ye; navnîşan hîn not e.'],
['Ez dikarim li vir bilêt nîşan bidim?','Na. Sverinav te dibe xizmeta fermî ya Västtrafik ji bo cure, biha, kirîn û nîşandana bilêta derbasdar. Bilêt nafiroşe û pere dayînê piştrast nake.'],
['Karên kurt û pêşketina lîstikê dê hebin?','Em karên vebijarkî bi armanc, çend gav û encam plan dikin: wek kontrola pirsgirêka rê an amadekirina nerîna planê. Gava qediyayî nayê wateya ku bajar pirsgirêk çareser kiriye. Xal, xelat û karên cîranan hîn tune ne.'],
['Proje dê çawa were fînanskirin?','Model nehat hilbijartin. Piştgirî û amûrên pereyî ji bo rêxistinan têne nirxandin, niştecih belaş bi kar tînin. Alîkarî ji bo xal û xelatên hevkaran fikir in, ne dahata sozdayî. Rêgez, ewlehî û pere berî destpêkê divê werin kontrolkirin.'],
['Dane dikarin şaş an kevn bin?','Erê. Çavkanî dikare negihîştî be, dane biguherin û kod şaşiyê hebe. Dem, herêm û orîjînalê kontrol bike. Kontrola têkçûyî nayê wê wateyê ku her tişt baş e.'],
['Piştre çi tê?','Nivîsên zelal, rawestgehên hilanî, guhertinên girîng, dîrok û hilbijartina cihê pirsgirêkê bi dest. Karên hemwelatî yên gav-bi-gav rêyek nû ne. Şopandin, xal, xelat û karên cîranan hîn tune ne.']
]}
};
