/* Progressive enhancement of the existing Om route. Public facts only; no network or storage. */
(() => {
  'use strict';
  const AUTHOR = Object.freeze({name:'Pavel Chuprunov',handle:'chup1runov',profile:'https://github.com/chup1runov'});
  const REPOSITORY_CREATED = '2026-09-21';
  const CONTACT = 'https://github.com/chup1runov/Sverinav/issues/new?template=contact-author.yml';
  const HISTORY = 'https://github.com/chup1runov/Sverinav/commits/main/';
  const COPY = {
"sv":{"by":"Personen bakom","role":"Initiativtagare och projektansvarig","why":"Varför finns Sverinav?","purpose":"Du ska kunna börja med din fråga, inte med namnet på rätt myndighet. Sverinav samlar en kort vardagsöversikt och hjälper dig vidare till den officiella källan eller tjänsten.","history":"När startade projektet?","created":"Kodarkivet skapades","dateNote":"Det är ett verifierbart datum för kodarkivet, inte ett påstående om när idén först uppstod. Första pilotområdet är Göteborg.","historyLink":"Se projektets historik","contact":"Skriv till Pavel","contactNote":"Offentlig kontakt via GitHub. Konto krävs. Alla kan läsa det du publicerar. Skicka inte personnummer, exakta adresser, lösenord eller andra känsliga uppgifter. Ingen privat support eller akutkanal.","faq":"Vanliga frågor","questions":[["Kostar det något?","Den nuvarande piloten kan användas utan konto eller betalning till Sverinav. Externa tjänster, till exempel biljetter, har egna villkor och avgifter."],["Vad fungerar redan och vad är planerat?","Väder och länsvarningar från SMHI, dokument från Riksdagen, öppna Göteborgsplaner och väghållarkontroll via NVDB är anslutna. Resor och vatten är än så länge länkar till officiella tjänster, inte inbyggda avgångar, biljetter eller avbrottsstatus."],["Gäller allt på startsidan mitt område?","Nej. Områdesvalet gäller väderprognosen. Varningarna gäller Västra Götaland och planlistan Göteborg. Personliga hållplatser och bevakningar är nästa steg, inte färdiga funktioner."],["Skickar Sverinav min felanmälan?","Nej. Du väljer och granskar själv uppgifterna och skickar i den officiella tjänsten. GPS-kontrollen gäller telefonens position; adressfältet är en anteckning, inte adressökning."],["Kan jag visa en biljett här?","Nej. Öppna Västtrafik To Go för en giltig biljett. Sverinav säljer inte biljetter och verifierar inte betalningar."],["Används AI?","AI-verktyg används som stöd i utvecklingen. Pilotens myndighetsdokument länkas till originalet; AI-genererade politiska sammanfattningar publiceras inte i den här versionen."],["Kan informationen vara fel eller gammal?","Ja. Källor kan vara otillgängliga, uppgifter kan ändras och kod kan ha fel. Kontrollera tid, geografisk omfattning och originalkälla innan du agerar. En misslyckad kontroll betyder inte att allt är lugnt."],["Är koden open source?","Koden är offentlig på GitHub, men en slutlig licens har inte valts. Offentlig åtkomst är inte samma sak som en fri licens."],["Vad händer härnäst?","Prioriterat är tydligare omfattning, valda hållplatser, relevanta förändringar och sparade datum. Manuell plats för ett vägfel ingår också i planen. Dessa förbättringar kräver ytterligare implementation och test."]]},
"en":{"by":"Who is behind it","role":"Project initiator and maintainer","why":"Why does Sverinav exist?","purpose":"Start with your question, not the name of the right authority. Sverinav combines a short everyday overview with a path to the official source or service.","history":"When did it start?","created":"Code repository created","dateNote":"This is a verifiable repository date, not a claim about when the idea first arose. The first pilot area is Gothenburg.","historyLink":"View project history","contact":"Write to Pavel","contactNote":"Public contact through GitHub. An account is required. Anyone can read what you publish. Do not include identity numbers, exact addresses, passwords or other sensitive information. Not private support or an emergency channel.","faq":"Common questions","questions":[["Does it cost anything?","The current pilot requires no account or payment to Sverinav. External services, such as tickets, have their own terms and charges."],["What works and what is planned?","SMHI forecasts and county warnings, Riksdag documents, open Gothenburg consultations and NVDB road-holder checks are connected. Travel and water are currently official links, not integrated departures, tickets or interruption status."],["Does the selected area apply to everything?","No. The area choice applies to the forecast. Warnings cover Västra Götaland and the plan list covers Gothenburg. Personal stops and watches are planned, not completed features."],["Does Sverinav submit my report?","No. You choose and review the information and submit it in the official service. GPS checks the phone’s position; the address field is a note, not an address search."],["Can I display a ticket here?","No. Open Västtrafik To Go for a valid ticket. Sverinav does not sell tickets or verify payments."],["Is AI used?","AI tools assist development. Official documents link to their originals; this version does not publish AI-generated political summaries."],["Can information be wrong or outdated?","Yes. Sources can be unavailable, information can change, and code can contain errors. Check the time, geographic scope and original before acting. A failed check does not mean everything is fine."],["Is the code open source?","The code is public on GitHub, but the final licence has not been selected. Public access is not the same as a free licence."],["What comes next?","Priorities are clearer scope, saved stops, relevant changes and saved dates. Choosing a road-problem location manually is also planned. These improvements still require implementation and testing."]]},
"ru":{"by":"Кто делает проект","role":"Инициатор и ответственный за проект","why":"Зачем нужен Sverinav?","purpose":"Начинай со своего вопроса, а не с поиска нужного ведомства. Sverinav объединяет короткую повседневную сводку и понятный путь к официальному источнику или сервису.","history":"Когда появился проект?","created":"Репозиторий кода создан","dateNote":"Это подтверждаемая дата создания репозитория, а не утверждение о дне появления идеи. Первый пилотный регион — Гётеборг.","historyLink":"Посмотреть историю проекта","contact":"Написать Павлу","contactNote":"Публичное обращение через GitHub. Нужен аккаунт. Сообщение видят все. Не указывай personnummer, точный адрес, пароли и другие чувствительные данные. Это не личная переписка и не экстренная служба.","faq":"Частые вопросы","questions":[["Это платно?","Для текущего пилота не нужны аккаунт или оплата Sverinav. Внешние сервисы, например билеты, имеют собственные условия и стоимость."],["Что уже работает, а что пока в планах?","Подключены прогноз и предупреждения SMHI по лену, документы Riksdagen, открытые обсуждения планов Гётеборга и проверка ответственного за дорогу через NVDB. Транспорт и вода пока представлены ссылками, а не встроенными отправлениями, билетами или статусами отключений."],["Выбранный район относится ко всей главной?","Нет. Он влияет на прогноз. Предупреждения относятся к Västra Götaland, а список планов — к Гётеборгу. Избранные остановки и подписки ещё не реализованы."],["Sverinav отправляет моё обращение?","Нет. Ты сам проверяешь сведения и отправляешь их в официальном сервисе. GPS проверяет положение телефона; поле адреса — примечание, а не поиск места."],["Можно показать здесь билет?","Нет. Действительный билет открывай в Västtrafik To Go. Sverinav не продаёт билеты и не проверяет оплату."],["Используется ли ИИ?","ИИ-инструменты помогают в разработке. Официальные документы доступны по ссылкам на оригинал; эта версия не публикует политические пересказы, созданные ИИ."],["Данные могут быть ошибочными или устаревшими?","Да. Источник может не отвечать, сведения — измениться, а код — содержать ошибки. Проверяй время, территорию действия и оригинал перед действием. Сбой проверки не означает, что всё спокойно."],["Исходный код свободный?","Код опубликован на GitHub, но окончательная лицензия ещё не выбрана. Публичный доступ не равнозначен свободной лицензии."],["Что будет дальше?","Приоритеты: точные подписи области действия, избранные остановки, значимые изменения и сохранённые даты. Также запланирован ручной выбор места дорожной проблемы. Это ещё предстоит реализовать и проверить."]]},
"uk":{"by":"Хто робить проєкт","role":"Ініціатор і відповідальний за проєкт","why":"Навіщо потрібен Sverinav?","purpose":"Починайте зі свого питання, а не з пошуку потрібного органу. Sverinav поєднує короткий щоденний огляд зі зрозумілим шляхом до офіційного джерела або сервісу.","history":"Коли з’явився проєкт?","created":"Репозиторій коду створено","dateNote":"Це підтверджена дата репозиторію, а не день появи ідеї. Перший пілотний регіон — Гетеборг.","historyLink":"Історія проєкту","contact":"Написати Павлу","contactNote":"Публічне звернення через GitHub. Потрібен акаунт. Повідомлення бачать усі. Не вказуйте personnummer, точну адресу, паролі чи інші чутливі дані. Це не приватне листування й не екстрена служба.","faq":"Часті питання","questions":[["Це платно?","Поточний пілот не потребує акаунта чи оплати Sverinav. Зовнішні сервіси, наприклад квитки, мають власні умови та вартість."],["Що вже працює?","Підключено прогноз і попередження SMHI для лену, документи Riksdagen, відкриті обговорення планів Гетеборга й перевірку відповідального за дорогу через NVDB. Транспорт і вода поки представлені посиланнями, а не вбудованими відправленнями, квитками чи статусами відключень."],["Обраний район стосується всієї головної?","Ні. Він впливає на прогноз. Попередження стосуються Västra Götaland, а перелік планів — Гетеборга. Обрані зупинки й підписки ще не реалізовані."],["Sverinav надсилає звернення?","Ні. Ви перевіряєте відомості й надсилаєте їх в офіційному сервісі. GPS перевіряє положення телефона; поле адреси — примітка, а не пошук місця."],["Можна показати тут квиток?","Ні. Чинний квиток відкривайте у Västtrafik To Go. Sverinav не продає квитки й не перевіряє оплату."],["Чи використовується ШІ?","Інструменти ШІ допомагають у розробці. Документи мають посилання на оригінал; ця версія не публікує політичні перекази, створені ШІ."],["Дані можуть бути помилковими чи застарілими?","Так. Джерела можуть не відповідати, відомості — змінюватися, а код — містити помилки. Перевіряйте час, територію й оригінал. Збій перевірки не означає, що все спокійно."],["Код має вільну ліцензію?","Код публічний на GitHub, але остаточну ліцензію ще не обрано. Публічний доступ не дорівнює вільній ліцензії."],["Що далі?","Пріоритети: точні підписи, обрані зупинки, важливі зміни й збережені дати. Також заплановано ручний вибір місця дорожньої проблеми. Це ще потрібно реалізувати й перевірити."]]},
"fi":{"by":"Hankkeen tekijä","role":"Hankkeen alullepanija ja ylläpitäjä","why":"Miksi Sverinav on olemassa?","purpose":"Aloita omasta kysymyksestäsi, älä oikean viranomaisen nimestä. Sverinav yhdistää lyhyen arjen katsauksen ja reitin viralliseen lähteeseen tai palveluun.","history":"Milloin hanke alkoi?","created":"Koodivarasto luotu","dateNote":"Päivä koskee todennettavaa koodivaraston luontia, ei idean syntymistä. Ensimmäinen pilottialue on Göteborg.","historyLink":"Katso hankkeen historia","contact":"Kirjoita Pavelille","contactNote":"Julkinen yhteydenotto GitHubissa. Tili vaaditaan. Kaikki voivat lukea julkaisusi. Älä lisää henkilötunnuksia, tarkkoja osoitteita, salasanoja tai arkaluonteisia tietoja. Ei yksityistä tukea eikä hätäpalvelu.","faq":"Usein kysyttyä","questions":[["Maksaako käyttö?","Nykyinen pilotti ei vaadi tiliä tai maksua Sverinaville. Ulkoisilla palveluilla, kuten lipuilla, on omat ehtonsa ja maksunsa."],["Mikä toimii jo?","SMHI:n ennuste ja läänin varoitukset, valtiopäivien asiakirjat, Göteborgin avoimet kuulemiset ja NVDB-tienpitäjätarkistus on yhdistetty. Liikenne ja vesi ovat vielä virallisia linkkejä, eivät lähtö-, lippu- tai katkotietointegraatioita."],["Koskeeko aluevalinta koko etusivua?","Ei. Valinta koskee ennustetta. Varoitukset koskevat Västra Götalandia ja suunnitelmat Göteborgia. Omat pysäkit ja seurannat eivät ole vielä valmiita."],["Lähettääkö Sverinav vikailmoituksen?","Ei. Tarkistat ja lähetät tiedot itse virallisessa palvelussa. GPS tarkistaa puhelimen paikan; osoitekenttä on muistiinpano, ei osoitehaku."],["Voinko näyttää lipun täällä?","Et. Avaa voimassa oleva lippu Västtrafik To Gossa. Sverinav ei myy lippuja eikä tarkista maksuja."],["Käytetäänkö tekoälyä?","Tekoälytyökalut tukevat kehitystä. Asiakirjat linkittävät alkuperäiseen; tässä versiossa ei julkaista tekoälyn tekemiä poliittisia yhteenvetoja."],["Voivatko tiedot olla vääriä tai vanhoja?","Kyllä. Lähteet voivat olla poissa käytöstä, tiedot muuttua ja koodissa olla virheitä. Tarkista aika, alue ja alkuperäinen lähde. Epäonnistunut tarkistus ei tarkoita, että kaikki on kunnossa."],["Onko koodi avointa lähdekoodia?","Koodi on julkinen GitHubissa, mutta lopullista lisenssiä ei ole valittu. Julkinen pääsy ei ole sama asia kuin vapaa lisenssi."],["Mitä seuraavaksi?","Etusijalla ovat selkeä laajuus, omat pysäkit, olennaiset muutokset ja tallennetut päivät. Myös tievian paikan valinta käsin on suunnitteilla. Nämä vaativat vielä toteutusta ja testausta."]]},
"es":{"by":"Quién está detrás","role":"Impulsor y responsable del proyecto","why":"¿Por qué existe Sverinav?","purpose":"Empieza por tu pregunta, no por el nombre de la autoridad correcta. Sverinav reúne un breve resumen cotidiano y el camino a la fuente o servicio oficial.","history":"¿Cuándo comenzó?","created":"Repositorio de código creado","dateNote":"Es una fecha verificable del repositorio, no del origen de la idea. La primera zona piloto es Gotemburgo.","historyLink":"Ver el historial","contact":"Escribir a Pavel","contactNote":"Contacto público por GitHub. Requiere cuenta. Cualquiera puede leer lo que publiques. No incluyas números personales, direcciones exactas, contraseñas ni datos sensibles. No es soporte privado ni un canal de emergencias.","faq":"Preguntas frecuentes","questions":[["¿Tiene coste?","El piloto actual no exige cuenta ni pago a Sverinav. Los servicios externos, como los billetes, tienen sus propias condiciones y tarifas."],["¿Qué funciona ya?","Están conectados el pronóstico y los avisos provinciales de SMHI, documentos del Parlamento, consultas de Gotemburgo y responsables de vías mediante NVDB. Transporte y agua son enlaces oficiales, no salidas, billetes ni estados de cortes integrados."],["¿La zona elegida se aplica a todo?","No. Solo al pronóstico. Los avisos cubren Västra Götaland y los planes Gotemburgo. Las paradas favoritas y los seguimientos aún no están implementados."],["¿Sverinav envía mi aviso?","No. Tú revisas y envías los datos en el servicio oficial. El GPS comprueba la posición del teléfono; la dirección es una nota, no una búsqueda."],["¿Puedo mostrar aquí un billete?","No. Abre Västtrafik To Go para mostrar un billete válido. Sverinav no vende billetes ni verifica pagos."],["¿Se utiliza IA?","Las herramientas de IA ayudan al desarrollo. Los documentos enlazan al original; esta versión no publica resúmenes políticos generados por IA."],["¿Puede haber datos incorrectos o antiguos?","Sí. Las fuentes pueden fallar, los datos cambiar y el código tener errores. Comprueba la hora, el alcance geográfico y el original. Un fallo no significa que todo esté bien."],["¿El código es libre?","El código es público en GitHub, pero no se ha elegido la licencia definitiva. Acceso público no equivale a licencia libre."],["¿Qué sigue?","Se priorizan un alcance claro, paradas guardadas, cambios relevantes y fechas guardadas. También se prevé elegir manualmente el lugar de un problema vial. Falta implementar y probar estas mejoras."]]},
"bs":{"by":"Ko stoji iza projekta","role":"Pokretač i odgovorna osoba projekta","why":"Zašto postoji Sverinav?","purpose":"Počni od svog pitanja, a ne od naziva nadležne institucije. Sverinav spaja kratak dnevni pregled s putem do službenog izvora ili usluge.","history":"Kada je projekat počeo?","created":"Repozitorij koda je kreiran","dateNote":"Ovo je provjerljiv datum repozitorija, ne datum nastanka ideje. Prvo pilot-područje je Göteborg.","historyLink":"Pogledaj historiju projekta","contact":"Piši Pavelu","contactNote":"Javni kontakt preko GitHuba. Potreban je račun. Svi mogu čitati objavu. Ne unosi personnummer, tačne adrese, lozinke ili osjetljive podatke. Nije privatna podrška ni hitna služba.","faq":"Česta pitanja","questions":[["Da li se plaća?","Trenutni pilot ne zahtijeva račun ni plaćanje Sverinavu. Vanjske usluge, poput karata, imaju vlastite uslove i cijene."],["Šta već radi?","Povezani su SMHI prognoza i okružna upozorenja, parlamentarni dokumenti, javne konsultacije Göteborga i provjera upravljača ceste kroz NVDB. Prijevoz i voda su službeni linkovi, ne ugrađeni polasci, karte ili status prekida."],["Važi li odabrano područje za sve?","Ne. Samo za prognozu. Upozorenja obuhvataju Västra Götaland, a planovi Göteborg. Omiljena stajališta i praćenja još nisu implementirana."],["Šalje li Sverinav moju prijavu?","Ne. Sam provjeravaš i šalješ podatke u službenoj usluzi. GPS provjerava položaj telefona; adresa je bilješka, ne pretraga mjesta."],["Mogu li ovdje pokazati kartu?","Ne. Važeću kartu otvori u Västtrafik To Go. Sverinav ne prodaje karte niti provjerava uplate."],["Koristi li se AI?","AI alati pomažu u razvoju. Dokumenti vode na originale; ova verzija ne objavljuje političke sažetke koje je stvorio AI."],["Mogu li podaci biti pogrešni ili zastarjeli?","Da. Izvori mogu biti nedostupni, podaci se mijenjati, a kod sadržavati greške. Provjeri vrijeme, područje i original. Neuspjela provjera ne znači da je sve u redu."],["Je li kod slobodan?","Kod je javan na GitHubu, ali konačna licenca nije odabrana. Javni pristup nije isto što i slobodna licenca."],["Šta slijedi?","Prioritet su jasniji opseg, spremljena stajališta, važne promjene i datumi. Planiran je i ručni izbor mjesta problema na cesti. Ovo još zahtijeva implementaciju i testiranje."]]},
"so":{"by":"Qofka mashruuca ka dambeeya","role":"Aasaasaha fikradda iyo masuulka mashruuca","why":"Maxaa Sverinav loo sameeyay?","purpose":"Ka bilow su’aashaada, halkii aad ka raadin lahayd magaca hay’adda saxda ah. Sverinav wuxuu isku keenaa warbixin maalinle ah oo kooban iyo jidka isha ama adeegga rasmiga ah.","history":"Goorma ayuu bilowday?","created":"Kaydka koodka waxaa la sameeyay","dateNote":"Tani waa taariikh la xaqiijin karo oo kaydka koodka ah, ma aha maalintii fikraddu dhalatay. Tijaabada koowaad waxay ka dhacaysaa Göteborg.","historyLink":"Eeg taariikhda mashruuca","contact":"U qor Pavel","contactNote":"Xiriir dadweyne oo GitHub ah. Akoon ayaa loo baahan yahay. Qof kasta ayaa arki kara qoraalkaaga. Ha gelin personnummer, cinwaan sax ah, furaha sirta ama xog xasaasi ah. Ma aha xiriir gaar ah ama adeeg degdeg ah.","faq":"Su’aalaha caanka ah","questions":[["Lacag ma laga bixiyaa?","Tijaabada hadda uma baahna akoon ama lacag loo bixiyo Sverinav. Adeegyada dibadda sida tigidhadu waxay leeyihiin shuruudo iyo qiimo u gaar ah."],["Maxaa hadda shaqeeya?","Saadaasha iyo digniinaha gobolka ee SMHI, dukumentiyada baarlamaanka, qorshayaasha Göteborg ee fikradaha furan iyo NVDB masuulka waddada ayaa ku xiran. Gaadiidka iyo biyuhu waa xiriirro rasmi ah, ma aha bixitaanno, tigidh ama xaalad biyo-joojin oo gudaha ku jira."],["Aagga aan doortay wax walba ma khuseeyaa?","Maya. Wuxuu khuseeyaa saadaasha. Digniinuhu waxay daboolaan Västra Götaland, qorshayaashuna Göteborg. Joogsiyada la jecel yahay iyo la socodka weli lama hirgelin."],["Sverinav ma diraa warbixintayda?","Maya. Adiga ayaa hubiya oo ku dira adeegga rasmiga ah. GPS wuxuu hubiyaa halka telefoonku joogo; cinwaanku waa qoraal xusuus ah, ma aha goob-raadin."],["Tigidh ma ku muujin karaa halkan?","Maya. Tigidh sax ah ka fur Västtrafik To Go. Sverinav ma iibiyo tigidh mana xaqiijiyo lacag bixinta."],["AI ma la isticmaalaa?","Qalabka AI wuxuu caawiyaa horumarinta. Dukumentiyadu waxay ku xiran yihiin asalka; noocan ma daabaco soo-koobid siyaasadeed oo AI sameeyay."],["Xogtu ma khaldan kartaa ama duugoobi kartaa?","Haa. Iluhu way maqnaan karaan, xogtu way is beddeli kartaa, koodkuna wuu khaldami karaa. Hubi waqtiga, aagga iyo asalka. Hubin fashilantay micnaheedu ma aha in wax walba fiican yihiin."],["Koodku ma leeyahay ruqsad xor ah?","Koodku waa dadweyne oo GitHub yaal, laakiin ruqsadda kama dambaysta ah lama dooran. Helitaanka dadweyne la mid ma aha ruqsad xor ah."],["Maxaa xiga?","Mudnaanta waa xad cad, joogsiyo la kaydiyo, isbeddello khuseeya iyo taariikho. Doorashada gacanta ee goobta ciladda waddada sidoo kale waa qorshe. Hirgelin iyo tijaabo ayaa weli loo baahan yahay."]]},
"ku":{"by":"Kesê li pişt projeyê","role":"Destpêker û berpirsiyarê projeyê","why":"Sverinav ji bo çi heye?","purpose":"Bi pirsa xwe dest pê bike, ne bi navê saziya rast. Sverinav kurteya rojane û rêya çavkanî an xizmeta fermî li hev dicivîne.","history":"Proje kengî dest pê kir?","created":"Depoya kodê hate afirandin","dateNote":"Ev dîroka depoya kodê ya ku dikare were kontrolkirin e, ne dîroka peydabûna fikrê. Pilota yekem li Göteborgê ye.","historyLink":"Dîroka projeyê bibîne","contact":"Ji Pavel re binivîse","contactNote":"Têkiliya giştî bi GitHub. Hesab pêwîst e. Her kes dikare nivîsa te bixwîne. Personnummer, navnîşana tam, şîfre an daneyên hestiyar nenivîse. Ev ne piştgiriya taybet an xeta awarte ye.","faq":"Pirsên gelemperî","questions":[["Bi pere ye?","Pilota niha hesab an pere ji bo Sverinav naxwaze. Xizmetên derve, wek bilêt, şert û bihayên xwe hene."],["Niha çi kar dike?","Pêşbîniya SMHI, hişyariyên herêmê, belgeyên parlamentoyê, planên Göteborgê yên vekirî û kontrola berpirsiyarê rê bi NVDB girêdayî ne. Rêwîtî û av hîn girêdanên fermî ne, ne derketin, bilêt an rewşa birîna avê ya hundirîn."],["Herêma hilbijartî ji bo her tiştî ye?","Na. Ji bo pêşbîniya hewayê ye. Hişyarî Västra Götaland û plan Göteborgê digirin. Rawestgehên bijarte û şopandin hîn ne amade ne."],["Sverinav rapora min dişîne?","Na. Tu bixwe daneyan kontrol dikî û di xizmeta fermî de dişînî. GPS cihê telefonê kontrol dike; navnîşan tenê not e, ne lêgerîna cihê."],["Ez dikarim li vir bilêt nîşan bidim?","Na. Bilêta derbasdar di Västtrafik To Go de veke. Sverinav bilêt nafiroşe û pere dayînê kontrol nake."],["AI tê bikaranîn?","Amûrên AI di pêşvebirinê de alîkar in. Belge girêdana orîjînalê didin; ev guherto kurteyên siyasî yên AI naweşîne."],["Dane dikarin şaş an kevn bin?","Erê. Çavkanî dikare negihîştî be, dane biguherin û kod şaşiyê hebe. Dem, herêm û orîjînalê kontrol bike. Kontrola têkçûyî nayê wê wateyê ku her tişt baş e."],["Kod bi lîsansa azad e?","Kod li GitHub giştî ye, lê lîsansa dawî nehatiye hilbijartin. Gihîştina giştî ne heman tiştê lîsansa azad e."],["Piştre çi tê?","Pêşî çarçoveya zelal, rawestgehên hilanî, guhertinên girîng û dîrokên hilanî ne. Hilbijartina cihê pirsgirêka rê bi dest jî di planê de ye. Ev hîn pêwîstî bi pêkanîn û testê hene."]]},
"ar":{"by":"من وراء المشروع","role":"صاحب المبادرة والمسؤول عن المشروع","why":"لماذا يوجد Sverinav؟","purpose":"ابدأ بسؤالك لا باسم الجهة الحكومية الصحيحة. يجمع Sverinav نظرة يومية مختصرة وطريقاً إلى المصدر أو الخدمة الرسمية.","history":"متى بدأ المشروع؟","created":"أُنشئ مستودع الكود في","dateNote":"هذا تاريخ موثّق للمستودع، وليس ادعاءً عن يوم ظهور الفكرة. المنطقة التجريبية الأولى هي غوتنبرغ.","historyLink":"عرض سجل المشروع","contact":"اكتب إلى Pavel","contactNote":"تواصل علني عبر GitHub. يلزم حساب. يمكن للجميع قراءة ما تنشره. لا تضف الرقم الشخصي أو العنوان الدقيق أو كلمات المرور أو بيانات حساسة. ليست مراسلة خاصة أو خدمة طوارئ.","faq":"أسئلة شائعة","questions":[["هل الاستخدام مدفوع؟","لا تتطلب النسخة التجريبية الحالية حساباً أو دفعاً إلى Sverinav. للخدمات الخارجية، مثل التذاكر، شروطها ورسومها الخاصة."],["ما الذي يعمل فعلاً؟","تم ربط توقعات SMHI وتحذيرات المقاطعة ووثائق البرلمان وخطط غوتنبرغ المفتوحة للتعليقات وفحص مسؤول الطريق عبر NVDB. النقل والمياه روابط رسمية حالياً وليست مواعيد أو تذاكر أو حالات انقطاع مدمجة."],["هل تنطبق المنطقة المختارة على الصفحة كلها؟","لا. الاختيار يخص توقعات الطقس. التحذيرات تخص Västra Götaland والخطط تخص غوتنبرغ. المحطات المفضلة والمتابعات لم تُنفّذ بعد."],["هل يرسل Sverinav بلاغي؟","لا. تراجع المعلومات وترسلها بنفسك في الخدمة الرسمية. يفحص GPS موقع الهاتف؛ حقل العنوان ملاحظة وليس بحثاً عن مكان."],["هل يمكنني عرض تذكرة هنا؟","لا. افتح Västtrafik To Go للحصول على تذكرة صالحة. لا يبيع Sverinav التذاكر ولا يتحقق من المدفوعات."],["هل يُستخدم الذكاء الاصطناعي؟","تساعد أدوات الذكاء الاصطناعي في التطوير. ترتبط الوثائق بمصادرها الأصلية؛ لا تنشر هذه النسخة ملخصات سياسية مولدة بالذكاء الاصطناعي."],["هل يمكن أن تكون البيانات خاطئة أو قديمة؟","نعم. قد تتعطل المصادر أو تتغير البيانات أو يحتوي الكود على أخطاء. تحقق من الوقت والنطاق الجغرافي والأصل قبل التصرف. فشل الفحص لا يعني أن كل شيء بخير."],["هل الكود مفتوح المصدر؟","الكود متاح للعامة على GitHub، لكن الترخيص النهائي لم يُختَر. الوصول العام لا يعادل ترخيصاً حراً."],["ما الخطوة التالية؟","الأولويات هي نطاق أوضح ومحطات محفوظة وتغييرات مهمة وتواريخ محفوظة. اختيار موقع مشكلة الطريق يدوياً مخطط أيضاً. ما زالت هذه التحسينات تحتاج إلى تنفيذ واختبار."]]},
"fa":{"by":"چه کسی پشت پروژه است","role":"آغازگر و مسئول پروژه","why":"Sverinav برای چیست؟","purpose":"از پرسش خود شروع کنید، نه از نام نهاد مناسب. Sverinav یک مرور کوتاه روزانه و مسیر رسیدن به منبع یا خدمت رسمی را کنار هم می‌آورد.","history":"پروژه چه زمانی شروع شد؟","created":"مخزن کد ایجاد شد","dateNote":"این تاریخ قابل‌تأیید مخزن است، نه ادعایی درباره روز پیدایش ایده. منطقه آزمایشی نخست یوتبری است.","historyLink":"دیدن تاریخچه پروژه","contact":"به Pavel بنویسید","contactNote":"تماس عمومی از طریق GitHub. حساب لازم است. همه می‌توانند نوشته شما را بخوانند. شماره شخصی، نشانی دقیق، رمز یا اطلاعات حساس ننویسید. این پشتیبانی خصوصی یا خدمت اضطراری نیست.","faq":"پرسش‌های رایج","questions":[["آیا هزینه دارد؟","نسخه آزمایشی فعلی حساب یا پرداخت به Sverinav نمی‌خواهد. خدمات بیرونی مانند بلیت شرایط و هزینه‌های خود را دارند."],["چه چیزهایی اکنون کار می‌کند؟","پیش‌بینی و هشدارهای استانی SMHI، اسناد پارلمان، طرح‌های باز یوتبری و بررسی مسئول راه با NVDB متصل‌اند. حمل‌ونقل و آب فعلاً پیوند رسمی هستند، نه زمان حرکت، بلیت یا وضعیت قطعی درون برنامه."],["آیا منطقه انتخابی بر همه صفحه اثر دارد؟","خیر. انتخاب برای پیش‌بینی هواست. هشدارها برای Västra Götaland و فهرست طرح‌ها برای یوتبری است. ایستگاه‌های برگزیده و پیگیری‌ها هنوز اجرا نشده‌اند."],["آیا Sverinav گزارش من را می‌فرستد؟","خیر. خودتان اطلاعات را بررسی و در خدمت رسمی ارسال می‌کنید. GPS موقعیت تلفن را بررسی می‌کند؛ کادر نشانی یادداشت است، نه جست‌وجوی مکان."],["می‌توانم اینجا بلیت نشان دهم؟","خیر. بلیت معتبر را در Västtrafik To Go باز کنید. Sverinav بلیت نمی‌فروشد و پرداخت را تأیید نمی‌کند."],["آیا از هوش مصنوعی استفاده می‌شود؟","ابزارهای هوش مصنوعی به توسعه کمک می‌کنند. اسناد به اصل پیوند دارند؛ این نسخه خلاصه‌های سیاسی تولیدشده با هوش مصنوعی منتشر نمی‌کند."],["ممکن است اطلاعات اشتباه یا قدیمی باشد؟","بله. منابع ممکن است قطع شوند، داده تغییر کند یا کد خطا داشته باشد. زمان، محدوده جغرافیایی و اصل را پیش از اقدام بررسی کنید. شکست بررسی به معنی آرام بودن همه‌چیز نیست."],["آیا کد مجوز آزاد دارد؟","کد در GitHub عمومی است ولی مجوز نهایی انتخاب نشده. دسترسی عمومی برابر با مجوز آزاد نیست."],["قدم بعدی چیست؟","اولویت‌ها محدوده روشن‌تر، ایستگاه‌های ذخیره‌شده، تغییرات مرتبط و تاریخ‌هاست. انتخاب دستی مکان مشکل راه هم در برنامه است. این موارد هنوز به اجرا و آزمایش نیاز دارند."]]}
  };
  function element(tag, text, className) {
    const node = document.createElement(tag);
    if (text !== undefined) node.textContent = text;
    if (className) node.className = className;
    return node;
  }
  function external(text, href, className) {
    const a = element('a', text + ' ↗', className);
    a.href = href; a.target = '_blank'; a.rel = 'noopener noreferrer';
    return a;
  }
  function disclosure(title, body) {
    const d = element('details', undefined, 'project-disclosure');
    d.append(element('summary', title));
    const content = element('div', undefined, 'project-answer');
    if (typeof body === 'string') content.append(element('p',body)); else content.append(body);
    d.append(content); return d;
  }
  function mount(root = document.getElementById('view')) {
    const stack = root?.querySelector('.about-stack');
    // Each SPA/language render creates a new stack. Never duplicate or replace form controls.
    if (!stack || stack.dataset.projectEnhanced || !stack.querySelector('#pilotFeedbackForm')) return;
    const lang = document.documentElement.lang || 'sv';
    const L = COPY[lang] || COPY.en;
    const locale = COPY[lang] ? lang : 'en';
    const author = element('section',undefined,'about-card project-author');
    author.id='projectAuthor'; author.lang=locale;
    author.append(element('h2',L.by));
    const name=external(AUTHOR.name,AUTHOR.profile,'project-author-name'); name.dir='ltr';
    author.append(name,element('p',L.role+' · @'+AUTHOR.handle));
    const contact=external(L.contact,CONTACT,'project-contact-button');
    contact.id='contactAuthor'; contact.setAttribute('aria-describedby','projectContactNote');
    const note=element('p',L.contactNote,'project-contact-note'); note.id='projectContactNote';
    author.append(contact,note);
    const story = element('section',undefined,'about-card project-story'); story.lang=locale;
    story.append(element('h2',L.why),element('p',L.purpose));
    const facts=element('div');
    const date=new Intl.DateTimeFormat(locale,{dateStyle:'long',timeZone:'Europe/Stockholm'}).format(new Date(REPOSITORY_CREATED+'T12:00:00Z'));
    const p=element('p',L.created+': '); const time=element('time',date);time.dateTime=REPOSITORY_CREATED;p.append(time);
    facts.append(p,element('p',L.dateNote),external(L.historyLink,HISTORY,'project-history-link'));
    const history=disclosure(L.history,facts); history.id='projectHistory';story.append(history);
    const faq=element('section',undefined,'project-faq');faq.id='projectFaq';faq.lang=locale;
    faq.append(element('h2',L.faq));
    L.questions.forEach(([q,a])=>faq.append(disclosure(q,a)));
    // Reuse existing privacy/source content and its translations. Only change presentation.
    const supplementary=[...stack.children].filter(n=>n.matches('section.about-card') && !n.matches('.about-card--notice,.about-meta,.feedback-card'));
    for (const section of supplementary) {
      const h=section.querySelector('h3');if(!h)continue;
      const d=disclosure(h.textContent,element('div'));
      d.classList.add('project-existing');
      const answer=d.querySelector('.project-answer');answer.replaceChildren();
      [...section.childNodes].filter(n=>n!==h).forEach(n=>answer.append(n));
      section.replaceWith(d);
    }
    // Keep the non-authority disclosure visible, and preserve existing local feedback behavior.
    const notice=stack.querySelector('.about-card--notice');
    if(notice)notice.after(author,story,faq);else stack.prepend(author,story,faq);
    stack.dataset.projectEnhanced='true';
  }
  globalThis.SverinavProjectAbout={COPY,AUTHOR,REPOSITORY_CREATED,CONTACT,mount};
  if(typeof document==='undefined')return;
  const root=document.getElementById('view');
  if(root){mount(root);new MutationObserver(()=>mount(root)).observe(root,{childList:true});}
})();
