"""Chromium checks with synthetic provider fixtures, not Safari/device testing."""
import asyncio,json,os,shutil
from pathlib import Path
from datetime import datetime,timezone,timedelta
from playwright.async_api import async_playwright,expect
BASE=os.getenv('BASE_URL','http://127.0.0.1:4173/Sverinav/')
ROOT=Path(__file__).resolve().parents[1]
OUT=Path(os.getenv('QA_OUTPUT','qa-output'));OUT.mkdir(exist_ok=True)
passed=[]
async def main():
 now=datetime.now(timezone.utc);iso=lambda d:d.isoformat().replace('+00:00','Z')
 forecast={'referenceTime':iso(now),'timeSeries':[{'time':iso(now+timedelta(hours=i)),'data':{'air_temperature':13+i/10,'wind_speed':2.7,'probability_of_precipitation':30}} for i in range(1,7)]}
 feed={'schemaVersion':1,'fetchedAt':iso(now),'sourceId':'riksdagen_open_data','sourceName':'Sveriges riksdag','items':[{'title':'Testdata — utskottsdokument','sourceUrl':'https://data.riksdagen.se/dokument/test.html','documentType':'Betänkande'}]}
 plan={'schemaVersion':1,'fetchedAt':iso(now),'sourceId':'goteborg_open_plans','sourceName':'Göteborgs Stad','sourceUrl':'https://goteborg.se/planochbyggprojekt','items':[{'title':'Testdata — samråd','deadline':(now+timedelta(days=3)).date().isoformat(),'sourceUrl':'https://goteborg.se/test-plan'}]}
 async with async_playwright() as pw:
  browser=await pw.chromium.launch(executable_path=shutil.which('chromium') or shutil.which('google-chrome'),args=['--no-sandbox'])
  context=await browser.new_context(viewport={'width':390,'height':844},locale='sv-SE',is_mobile=True,has_touch=True,service_workers='block')
  async def routes(route):
   url=route.request.url
   if 'opendata-download-metfcst' in url:await route.fulfill(json=forecast,headers={'access-control-allow-origin':'*'})
   elif 'opendata-download-warnings' in url:await route.fulfill(body='[]',content_type='application/json',headers={'access-control-allow-origin':'*'})
   elif url.endswith('data/riksdagen-decisions.json'):await route.fulfill(json=feed)
   elif url.endswith('data/goteborg-open-plans.json'):await route.fulfill(json=plan)
   elif url.startswith(BASE):await route.continue_()
   else:await route.abort()
  await context.route('**/*',routes)
  page=await context.new_page();errors=[]
  page.on('pageerror',lambda error:errors.append(str(error)))
  await page.goto(BASE)
  await expect(page.locator('#dailyWeather .weather-main')).to_be_visible()
  await expect(page.locator('#homeOpenPlans .plan-card')).to_have_count(1)
  await expect(page.locator('#homeDecisions')).to_have_count(0)
  await expect(page.locator('#dailyWarnings')).to_contain_text('Inga meddelanden')
  assert await page.evaluate('document.documentElement.scrollWidth <= innerWidth')
  passed.append('Compact Idag keeps the current forecast, scoped warning status and one civic deadline')
  await expect(page.locator('#weatherDetails')).not_to_have_attribute('open','')
  await expect(page.locator('.weather-hours')).not_to_be_visible()
  await page.locator('#weatherDetails>summary').focus();await page.keyboard.press('Enter')
  await expect(page.locator('.weather-hours')).to_be_visible()
  await page.locator('#weatherDetails>summary').click()
  await expect(page.locator('.weather-hours')).not_to_be_visible()
  await expect(page.locator('#weatherDetails>summary')).to_be_focused()
  passed.append('Weather details disclose by keyboard and tap without navigation or lost focus')
  await page.locator('#areaDetails>summary').click()
  await expect(page.locator('#areaNotice')).to_be_visible()
  await page.select_option('#weatherArea','hisingen')
  await expect(page.locator('#dailyWeather .weather-main')).to_be_visible()
  assert await page.evaluate("localStorage.getItem('sverinav-weather-area')")=='hisingen'
  await expect(page.locator('#currentWeatherArea')).to_have_text('Hisingen')
  await page.locator('#areaDetails>summary').click()
  passed.append('Coarse area preference is adjustable with visible privacy notice and without GPS')
  journey=await page.locator('#compactJourney').bounding_box()
  nav=await page.locator('.bottom-nav').bounding_box()
  assert journey['y']+journey['height']<nav['y'],'Primary next action below fold at 390x844'
  passed.append('Forecast, warning state and journey action fit above bottom navigation at 390x844')
  await page.locator('#serviceDetails>summary').click()
  await expect(page.locator('#serviceDetails')).to_contain_text('Status visas inte här')
  await expect(page.locator('#serviceDetails')).to_contain_text('Sverinav säljer')
  await page.locator('#serviceDetails>summary').click()
  passed.append('Water and tickets remain clearly labelled external handoffs under More services')
  await page.evaluate('scrollTo(0,0)');await page.screenshot(path=str(OUT/'compact-mobile.png'),full_page=True)
  await page.screenshot(path=str(OUT/'compact-first-screen.png'))
  await page.locator('.bottom-nav [data-screen="beslut"]').click()
  await expect(page.locator('#decisionList .decision-live-link')).to_have_count(1)
  passed.append('Riksdag documents remain available in Beslut instead of duplicated on home')
  await page.locator('[data-screen="rapportera"]').first.click()
  await page.fill('#reportDescription','Test only — do not submit')
  await page.click('#languageButton');await page.click('[data-language="ru"]')
  await expect(page.locator('#reportDescription')).to_have_value('Test only — do not submit')
  passed.append('Language switch preserves the in-memory report draft')
  await page.evaluate("document.querySelector('.skip-link').click()")
  assert page.url.endswith('#rapportera')
  passed.append('Skip link does not reset the route')
  await page.click('#aboutButton')
  await page.evaluate("() => { navigator.clipboard.writeText=async()=>{throw new Error('denied')};document.execCommand=()=>false; }")
  await page.fill('#pilotFeedbackTask','Copy test');await page.click('#copyPilotFeedback')
  await expect(page.locator('#pilotFeedbackStatus')).to_contain_text('Не удалось')
  assert await page.locator('body > textarea').count()==0
  passed.append('Clipboard denial is not reported as success and leaves no hidden textarea')
  for lang in ['sv','en','ar','so','fa','fi','bs','ku','es','ru','uk']:
   await page.click('#languageButton');await page.click(f'[data-language="{lang}"]')
   assert await page.locator('html').get_attribute('lang')==lang
   assert await page.locator('html').get_attribute('dir')==('rtl' if lang in ('ar','fa') else 'ltr')
   await page.locator('.bottom-nav [data-screen="home"]').click()
   await expect(page.locator('#dailyWeather .weather-main')).to_be_visible()
   for width in [320,390]:
    await page.set_viewport_size({'width':width,'height':844})
    assert await page.evaluate('document.documentElement.scrollWidth <= innerWidth'),f'Overflow {lang} {width}'
   if lang=='ar':await page.screenshot(path=str(OUT/'compact-rtl.png'),full_page=True)
  passed.append('All eleven languages and RTL have no horizontal overflow at 320 and 390px')
  await page.click('#languageButton');await page.click('[data-language="sv"]')
  await page.set_viewport_size({'width':1280,'height':900})
  assert await page.evaluate('document.documentElement.scrollWidth <= innerWidth')
  await page.screenshot(path=str(OUT/'compact-desktop.png'),full_page=True)
  passed.append('Desktop remains readable and bounded rather than stretched into a dashboard')
  await page.click('#languageButton')
  await expect(page.locator('.language-option[aria-pressed="true"]')).to_be_focused()
  await page.locator('.language-option').last.focus();await page.keyboard.press('Tab')
  await expect(page.locator('#closeLanguageButton')).to_be_focused()
  await page.keyboard.press('Escape');await expect(page.locator('#languageButton')).to_be_focused()
  passed.append('Language dialog traps focus and restores it on Escape')
  await page.goto(BASE+'#ansvar');await page.fill('#issue','Hål i vägen');await page.click('#findOwner')
  await expect(page.locator('[data-road-resolve]')).to_be_visible()
  await page.evaluate("Object.defineProperty(navigator.geolocation,'getCurrentPosition',{value:(ok,fail)=>fail({code:1})})")
  await page.click('[data-road-resolve]');await expect(page.locator('[data-road-live]')).not_to_be_empty()
  passed.append('Geolocation denial is a visible error, not a fabricated road holder')
  await page.evaluate("globalThis.testUncertain=roadMatchUncertain({ambiguous:true,accuracyMeters:5,distanceMeters:2});globalThis.testRoute=officialReportUrl({holderType:'statlig',ambiguous:true,accuracyMeters:5,distanceMeters:2})")
  assert await page.evaluate('testUncertain && testRoute===null')
  passed.append('Ambiguous road match cannot auto-route to one recipient')
  await page.goto(BASE);await page.set_viewport_size({'width':390,'height':844})
  await page.evaluate("() => { SverinavDaily.loadWarnings=async()=>({fetchedAt:new Date().toISOString(),payload:[{title:'Testdata — kraftigt regn',area:'Testområde',levelLabel:'Gul varning'}]}); }")
  await page.click('#dailyRefresh');await expect(page.locator('#dailyWarnings .warning-item')).to_be_visible()
  assert await page.locator('#dailyWarnings details').count()==0
  passed.append('Active warning text is visible immediately, never hidden in a disclosure')
  await page.screenshot(path=str(OUT/'compact-warning.png'),full_page=True)
  await page.evaluate("() => { SverinavDaily.loadWarnings=async()=>{throw new Error('offline')}; }")
  await page.click('#dailyRefresh');await expect(page.locator('#dailyWarnings .source-unavailable')).to_be_visible()
  await expect(page.locator('#dailyWarnings')).not_to_contain_text('Inga meddelanden')
  passed.append('Warning-source failure cannot appear as all-clear or remain hidden')
  await page.evaluate("() => { SverinavDaily.loadForecast=async()=>{throw new Error('offline')}; }")
  await page.click('#dailyRefresh');await expect(page.locator('#dailyWeather .source-unavailable')).to_be_visible()
  passed.append('Weather-source failure is visible even with collapsed weather details')
  await page.add_style_tag(content='p,small,.compact-meta,.compact-row-copy,.compact-summary-hint,.compact-forecast-metrics {font-size:24px!important} .bottom-nav button{font-size:20px!important}')
  assert await page.evaluate('document.documentElement.scrollWidth <= innerWidth')
  await expect(page.locator('#dailyWarnings .source-unavailable')).to_be_visible()
  passed.append('Large text can reflow vertically without hiding source-error messages')
  assert errors==[], '\n'.join(errors)
  await context.close()
  blocked=await browser.new_context(service_workers='block',locale='sv-SE');await blocked.route('**/*',routes)
  await blocked.add_init_script("Storage.prototype.getItem=()=>{throw new Error('denied')};Storage.prototype.setItem=()=>{throw new Error('denied')}")
  bpage=await blocked.new_page();await bpage.goto(BASE);await expect(bpage.locator('#todayScreen')).to_be_visible()
  passed.append('Startup tolerates disabled storage')
  await blocked.close();await browser.close()
 OUT.joinpath('browser-results.json').write_text(json.dumps({'passed':passed,'limitations':['Chromium, not real iPhone/WebKit','Synthetic fixtures; live API contracts checked separately','No real payment or official report submitted']},ensure_ascii=False,indent=2))
 print('\n'.join('PASS '+item for item in passed))
asyncio.run(main())
