import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {decodeEntities,parsePlans} from '../scripts/fetch-goteborg-open-plans.mjs';
const ctx=vm.createContext({console,URL,Date,Intl,setTimeout,clearTimeout,AbortController,Headers,Response,fetch,localStorage:{getItem(){throw new Error('disabled');},setItem(){throw new Error('disabled');}}});
for(const file of ['civic-core.js','daily-data.js','goteborg-plans.js'])vm.runInContext(await readFile(new URL('../'+file,import.meta.url),'utf8'),ctx);
const C=ctx.SverinavCore,D=ctx.SverinavDaily;
const now=Date.parse('2026-09-23T10:15:00Z');
const forecast={referenceTime:'2026-09-23T10:00:00Z',timeSeries:[{time:'2026-09-23T11:00:00Z',data:{air_temperature:13,wind_speed:4,probability_of_precipitation:30}}]};
const warning=(id=14,extra={})=>[{event:{sv:'Test warning'},warningAreas:[{id:1,affectedAreas:[{id}],warningLevel:{code:'YELLOW'},areaName:{sv:'TEST'},...extra}]}];
test('storage restrictions do not crash app',()=>{assert.equal(C.storage.get('x'),null);assert.equal(C.storage.set('x','y'),false);});
test('dates reject null, rollover and future feed timestamp',()=>{assert.equal(C.timestamp(null),null);assert.equal(C.dateOnly('2026-02-30'),false);assert.throws(()=>C.feed({schemaVersion:1,sourceId:'test',fetchedAt:'2099-01-01T00:00:00Z',items:[]},'test',[]));});
test('URLs reject script, deceptive hostname and credentials',()=>{for(const u of ['javascript:alert(1)','https://goteborg.se.evil.example/x','https://u:p@goteborg.se/x'])assert.equal(C.officialUrl(u,['goteborg.se']),null);assert.equal(C.officialUrl('https://goteborg.se/x',['goteborg.se']),'https://goteborg.se/x');});
test('escaped external content is inert',()=>assert.equal(C.escape('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;'));
test('SMHI uses SNOW flat data and future forecast time',()=>{const f=D.forecast(forecast,now);assert.equal(f.rows[0].data.air_temperature,13);});
test('old SMHI schema, missing sentinel and stale forecasts fail',()=>{assert.throws(()=>D.forecast({referenceTime:forecast.referenceTime,timeSeries:[{validTime:'2026-09-23T11:00:00Z',parameters:[]}]},now));assert.throws(()=>D.forecast({...forecast,referenceTime:'2026-09-22T00:00:00Z'},now));assert.equal(D.finite(9999),false);assert.equal(D.finite(null),false);});
test('warning result is county-scoped and expires correctly',()=>{assert.equal(D.warnings(warning(),now).length,1);assert.equal(D.warnings(warning(12),now).length,0);assert.equal(D.warnings(warning(14,{approximateEnd:'2026-09-23T10:00:00Z'}),now).length,0);assert.equal(D.warnings(warning(14,{approximateStart:'2026-09-25T10:00:00Z'}),now).length,0);});
test('missing warning schema must not become all-clear',()=>{assert.throws(()=>D.warnings({error:'offline'},now));assert.throws(()=>D.warnings([{event:{},warningAreas:[{}]}],now));assert.equal(D.warnings([],now).length,0);});
test('Stockholm cutoff is inclusive until local midnight, including DST',()=>{assert.equal(C.stockholmDay(Date.parse('2026-09-23T21:59:00Z')),'2026-09-23');assert.equal(C.stockholmDay(Date.parse('2026-09-23T22:00:00Z')),'2026-09-24');assert.equal(C.stockholmDay(Date.parse('2026-12-23T23:00:00Z')),'2026-12-24');});
test('malformed feed differs from valid empty',()=>{const f={schemaVersion:1,sourceId:'test',fetchedAt:new Date().toISOString(),items:[]};assert.equal(C.feed(f,'test',[]),f);assert.throws(()=>C.feed({...f,items:null},'test',[]));assert.throws(()=>C.feed({...f,error:'offline'},'test',[]));});
test('HTML scraper preserves uppercase Swedish letters',()=>assert.equal(decodeEntities('&Aring; &aring; &Auml; &Ouml;'),'Å å Ä Ö'));
test('HTML scraper fails when an open deadline cannot be associated with a valid item',()=>assert.throws(()=>parsePlans('<p>Synpunkter tas emot till och med 2026-09-30</p>','2026-09-23')));
test('HTML scraper permits genuine absence after all deadlines passed',()=>assert.equal(parsePlans('<p>Synpunkter tas emot till och med 2026-09-22</p>','2026-09-23').length,0));
