import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const ctx=vm.createContext({});
vm.runInContext(await readFile('folkoop-core.js','utf8'),ctx);
vm.runInContext(await readFile('folkoop-copy.js','utf8'),ctx);
const C=ctx.FolkoopCore,I=ctx.FolkoopCopy;
const memory=()=>{const values=new Map();return{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k),values};};
const item={id:'safe-123',kind:'project',title:'Together',body:'Build a workshop'};
test('expanded social navigation includes Profile, Home, social, cooperation and utility sections',()=>{for(const k of ['me','home','messages','people','communities','together','projects','city','center','settings','about'])assert(C.ROUTES.includes(k));assert(!C.ROUTES.includes('core'));assert.equal(I.COPY.ru.me,'Профиль');assert.equal(I.COPY.ru.communities,'Сообщества');assert.equal(I.COPY.ru.settings,'Настройки');assert.equal(I.COPY.ru.aboutPage,'О нас');});
test('routes reject unknown paths and executable values',()=>{assert.equal(C.route('#/projects'),'projects');assert.equal(C.route('#javascript:alert(1)'),'home');assert.equal(C.route('#/constructor'),'home');});
test('eleven existing language choices and native navigation labels are retained',()=>{assert.equal(C.LANGS.length,11);for(const lang of C.LANGS)for(const k of ['home','messages','people','communities','together','projects','city','center','me','settings','aboutPage','partial'])assert(I.COPY[lang][k]);});
test('partial shell translations are explicitly disclosed',()=>{assert.equal(I.FULL.length,3);assert(I.COPY.uk.partial.includes('англійською'));});
test('local workspace never writes before consent',()=>{const s=memory(),w=C.workspace(s);w.profile({name:'Test'});w.add(item);assert.equal(s.values.size,0);assert.equal(w.get().drafts.length,1);assert.equal(w.isPersistent(),false);});
test('consented data persists and reloads',()=>{const s=memory(),w=C.workspace(s);w.add(item);assert(w.remember(true));assert.equal(C.workspace(s).get().drafts[0].title,'Together');});
test('revoking persistence removes only the FOLKOOP key, retains in-memory work',()=>{const s=memory(),w=C.workspace(s);s.setItem('unrelated','keep');w.add(item);w.remember(true);assert(w.remember(false));assert.equal(s.getItem(C.KEY),null);assert.equal(s.getItem('unrelated'),'keep');assert.equal(w.get().drafts.length,1);});
test('blocked and malformed storage do not prevent use',()=>{const w=C.workspace({getItem(){throw Error('denied');},setItem(){throw Error('denied');}});assert.equal(w.get().drafts.length,0);assert.equal(w.remember(true),false);assert(w.add(item).ok);const s=memory();s.setItem(C.KEY,'{bad');assert.equal(C.workspace(s).get().drafts.length,0);});
test('unsupported schema versions are not silently overwritten',()=>{const s=memory();s.setItem(C.KEY,'{"version":9,"drafts":[]}');const w=C.workspace(s);assert.equal(w.isPersistent(),false);w.add(item);assert.equal(s.getItem(C.KEY),'{"version":9,"drafts":[]}');});
test('stored data is allowlisted and length-bounded',()=>{const v=C.clean({profile:{name:'x'.repeat(100),city:'Göteborg'.repeat(30),coordinates:[1,2],secret:'no'},drafts:[{...item,id:'<svg onload=x>'}]});assert.equal(v.profile.name.length,60);assert.equal(v.profile.city.length,120);assert.equal(v.profile.secret,undefined);assert.equal(v.drafts.length,0);});
test('draft IDs cannot inject attributes',()=>{const w=C.workspace();assert.equal(w.add({...item,id:'x" onclick="alert(1)'}).ok,false);});
test('content escaping protects render paths',()=>{assert.equal(C.escape('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;');});
test('own completion toggles and deletion work without publishing',()=>{const w=C.workspace();w.add(item);w.toggle(item.id);assert(w.get().drafts[0].done);w.remove(item.id);assert.equal(w.get().drafts.length,0);});
test('duplicate IDs and over-limit drafts are rejected',()=>{const w=C.workspace();w.add(item);assert.equal(w.add(item).ok,false);for(let i=1;i<100;i++)assert(w.add({...item,id:'id-'+i}).ok);assert.equal(w.add({...item,id:'extra'}).ok,false);});
test('storage failure after consent returns failure while preserving in-memory edit',()=>{const s=memory(),w=C.workspace(s);w.remember(true);s.setItem=()=>{throw Error('quota');};assert.equal(w.profile({name:'Latest',city:'Göteborg'}),false);assert.equal(w.get().profile.name,'Latest');assert.equal(w.get().profile.city,'Göteborg');});
test('returned snapshots cannot mutate live state',()=>{const w=C.workspace();w.add(item);w.get().drafts[0].title='changed';assert.equal(w.get().drafts[0].title,'Together');});
test('erase resets profile, drafts and consent without clearing unrelated preferences',()=>{const s=memory(),w=C.workspace(s);s.setItem('sverinav-language','ru');w.profile({name:'Test'});w.add(item);w.remember(true);assert(w.clear());assert.equal(w.get().drafts.length,0);assert.equal(w.get().profile.name,'');assert.equal(w.isPersistent(),false);assert.equal(s.getItem('sverinav-language'),'ru');});
test('new shell has no third-party network calls or payment simulation',async()=>{const s=await readFile('folkoop.js','utf8');assert(!/\bfetch\(/.test(s));assert(!/WebSocket|sendBeacon/.test(s));assert(s.includes("e.origin!==location.origin"));assert(s.includes("e.source!==frame.contentWindow"));});
