"""FOLKOOP shell regression. Chromium emulation; no live accounts or real submissions."""
import asyncio,json,os,shutil
from pathlib import Path
from playwright.async_api import async_playwright,expect
BASE=os.getenv('BASE_URL','http://127.0.0.1:4173/Sverinav/')
OUT=Path(os.getenv('QA_OUTPUT','qa-output'));OUT.mkdir(exist_ok=True)
async def main():
 results=[]
 async with async_playwright() as pw:
  browser=await pw.chromium.launch(executable_path=shutil.which('chromium') or shutil.which('google-chrome'),args=['--no-sandbox'])
  context=await browser.new_context(viewport={'width':1280,'height':960},locale='sv-SE',service_workers='block')
  async def local_only(route):
   if route.request.url.startswith(BASE):await route.continue_()
   else:await route.abort()
  await context.route('**/*',local_only)
  await context.add_init_script("localStorage.setItem('folkoop-onboarding-v1','done')")
  page=await context.new_page();errors=[]
  page.on('pageerror',lambda error:errors.append(str(error)))
  await page.goto(BASE)
  await expect(page.locator('#nav a')).to_have_count(11)
  await page.select_option('#language','ru')
  await expect(page.locator('h1')).to_contain_text('Находи людей')
  assert await page.evaluate('document.documentElement.scrollWidth<=innerWidth')
  await page.screenshot(path=str(OUT/'folkoop-desktop.png'),full_page=True)
  results.append('FOLKOOP root, brand asset and eleven ordered destinations')
  await page.evaluate("location.hash='#/me'")
  await page.fill('[name="name"]','Test User')
  await page.fill('[name="city"]','Göteborg')
  await page.fill('[name="skills"]','Repair, design')
  await page.click('#profileForm button[type="submit"]')
  assert await page.evaluate("localStorage.getItem('folkoop-workspace-v1')") is None
  await expect(page.locator('#status')).to_contain_text('сессии')
  results.append('My page saves in memory without a compulsory account or storage consent')
  await page.evaluate("location.hash='#/projects'")
  await page.click('[data-create="project"]')
  await page.fill('#draftForm [name="title"]','Workshop <img src=x onerror=alert(1)>')
  await page.fill('#draftForm [name="body"]','A private project, not a published listing.')
  await page.click('#draftForm button[type="submit"]')
  await expect(page.locator('.draft')).to_have_count(1)
  assert await page.locator('.draft img').count()==0
  await page.fill('#draftSearch','not-found')
  await expect(page.locator('#draftList')).to_contain_text('Ничего не найдено')
  await page.fill('#draftSearch','Workshop')
  await expect(page.locator('.draft')).to_have_count(1)
  results.append('Create and search a private project; HTML entered by a user is text, not executable')
  await page.evaluate("location.hash='#/me'");await page.check('#remember')
  await page.reload();await expect(page.locator('[name="name"]')).to_have_value('Test User')
  await expect(page.locator('.draft')).to_have_count(1)
  results.append('Opt-in browser storage restores profile and drafts')
  async with page.expect_download() as download:
   await page.click('[data-action="export"]')
  await (await download.value).save_as(str(OUT/'test-local-export.json'))
  exported=json.loads(OUT.joinpath('test-local-export.json').read_text())
  assert exported['profile']['name']=='Test User'
  assert exported['profile']['city']=='Göteborg'
  results.append('Export contains local profile city and private FOLKOOP workspace')
  await page.evaluate("location.hash='#/city'")
  city=page.frame_locator('#cityFrame')
  await expect(city.locator('.brand')).to_have_text('FOLKOOP')
  await expect(city.locator('html')).to_have_attribute('lang','ru')
  await city.locator('.bottom-nav [data-screen="rapportera"]').click()
  await city.locator('#reportDescription').fill('Private test draft — do not submit')
  await page.evaluate("location.hash='#/me'");await page.evaluate("location.hash='#/city'")
  await expect(city.locator('#reportDescription')).to_have_value('Private test draft — do not submit')
  await page.select_option('#language','en')
  await expect(city.locator('html')).to_have_attribute('lang','en')
  await expect(city.locator('#reportDescription')).to_have_value('Private test draft — do not submit')
  results.append('City stays integrated and retains an unsubmitted report across navigation/language changes')
  await page.evaluate("location.hash='#/center'")
  await expect(page.locator('#workspace')).to_contain_text('no open venue')
  await page.click('#messageLink');await expect(page.locator('#workspace')).to_contain_text('does not simulate')
  results.append('No fictitious venue, members, payments or message delivery')
  for lang in ['sv','en','ar','so','fa','fi','bs','ku','es','ru','uk']:
   await page.select_option('#language',lang)
   for width in [320,390,1280]:
    await page.set_viewport_size({'width':width,'height':844})
    assert await page.evaluate('document.documentElement.scrollWidth<=innerWidth'),f'{lang}/{width} overflow'
   assert await page.locator('html').get_attribute('dir')==('rtl' if lang in ('ar','fa') else 'ltr')
  results.append('All eleven navigation languages, RTL, and no horizontal overflow at 320/390/1280px')
  await page.select_option('#language','ru');await page.set_viewport_size({'width':390,'height':844})
  await page.evaluate("location.hash='#/me'")
  page.on('dialog',lambda d:d.accept())
  await page.click('[data-action="clear"]')
  await expect(page.locator('[name="name"]')).to_have_value('')
  assert await page.evaluate("localStorage.getItem('folkoop-workspace-v1')") is None
  await page.screenshot(path=str(OUT/'folkoop-my-page-mobile.png'),full_page=True)
  await page.click('#brandHome');await page.screenshot(path=str(OUT/'folkoop-mobile.png'),full_page=True)
  results.append('Erase removes only FOLKOOP local data; mobile screens captured')
  assert not errors,errors
  await context.close()
  blocked=await browser.new_context(service_workers='block')
  await blocked.route('**/*',local_only)
  await blocked.add_init_script("Storage.prototype.getItem=()=>{throw Error('blocked')};Storage.prototype.setItem=()=>{throw Error('blocked')}")
  b=await blocked.new_page();await b.goto(BASE+'#/me');await expect(b.locator('#profileForm')).to_be_visible()
  await b.fill('[name="name"]','Memory');await b.click('#profileForm button[type="submit"]')
  await expect(b.locator('#status')).not_to_be_empty()
  results.append('Blocked storage does not prevent starting or editing My page')
  await blocked.close()
  offline=await browser.new_context(service_workers='allow',locale='en-US')
  await offline.add_init_script("localStorage.setItem('folkoop-onboarding-v1','done');localStorage.setItem('folkoop-workspace-v1',JSON.stringify({version:1,profile:{name:'Offline',city:'Göteborg',skills:'',about:''},drafts:[]}))")
  op=await offline.new_page();await op.goto(BASE)
  await op.evaluate('navigator.serviceWorker.ready');await op.wait_for_function('!!navigator.serviceWorker.controller')
  await offline.set_offline(True);await op.reload()
  await expect(op.locator('#nav a')).to_have_count(11)
  await op.click('#nav a[href="#/city"]')
  await expect(op.frame_locator('#cityFrame').locator('#view')).not_to_be_empty()
  results.append('Installed shell and embedded City entry load offline; no fabricated source success')
  await offline.close();await browser.close()
 OUT.joinpath('folkoop-results.json').write_text(json.dumps({'passed':results,'limitations':['Chromium only, not a real iPhone/Safari check','No live backend, users, payments or official submissions','New detailed shell copy currently sv/en/ru; other navigation locales disclose English fallback']},ensure_ascii=False,indent=2))
 print('\n'.join('PASS '+x for x in results))
asyncio.run(main())
