import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const ctx=vm.createContext({URL,AbortController,setTimeout,clearTimeout});
vm.runInContext(await readFile('network-client.js','utf8'),ctx);
const N=ctx.FolkoopNetwork;
const cfg={enabled:true,url:'https://abcdefghijklmnopqrst.supabase.co',publishableKey:'sb_publishable_example_for_tests_only'};
const uid='11111111-1111-4111-8111-111111111111',cid='22222222-2222-4222-8222-222222222222';
const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json'}});
function setup(extra){const calls=[];let now=1000;
 const c=N.client(cfg,{clock:()=>now,transport:async(url,o)=>{calls.push({url,...o});if(extra){const r=await extra(url,o);if(r)return r;}
 if(url.endsWith('/verify'))return json({access_token:'test-token',expires_in:100,refresh_token:'never-store'});
 if(url.endsWith('/user'))return json({id:uid,email:'synthetic@example.test'});
 if(url.includes('/rpc/'))return json(null);return json([]);
 }});return{c,calls,expire(){now+=200000;},login:()=>c.verify('synthetic@example.test','123456')};}
test('disabled configuration never sends requests',async()=>{const c=N.client({enabled:false},{transport:()=>{throw Error('MUST_NOT_CALL');}});assert(!c.enabled);await assert.rejects(c.requestCode('test@example.test'),e=>e.code==='DISABLED');});
test('configuration fails closed without HTTPS project and publishable key',()=>{for(const change of [{url:'http://abcdefghijklmnopqrst.supabase.co'},{url:'https://attacker.example'},{url:cfg.url+'/other'},{url:cfg.url+'?token=x'},{url:'https://x@abcdefghijklmnopqrst.supabase.co'},{publishableKey:'sb_secret_DO_NOT_SHIP'},{publishableKey:'eyJlegacyJWT'}])assert.throws(()=>N.client({...cfg,...change}),e=>e.code==='CONFIG');});
test('OTP bootstrap may create the first Auth user without secrets in URL',async()=>{const s=setup();await s.c.requestCode('test@example.test');const r=s.calls[0];assert.equal(r.method,'POST');assert.equal(JSON.parse(r.body).create_user,true);assert(!r.url.includes('test@'));assert.equal(r.credentials,'omit');assert.equal(r.cache,'no-store');assert.equal(r.redirect,'error');assert(!r.headers.Authorization);});
test('bad email rejected before transport',async()=>{const s=setup();await assert.rejects(s.c.requestCode('invalid'),e=>e.code==='INVALID_INPUT');assert.equal(s.calls.length,0);});
test('bad OTP rejected before transport',async()=>{const s=setup();await assert.rejects(s.c.verify('test@example.test','abcdef'),e=>e.code==='INVALID_INPUT');assert.equal(s.calls.length,0);});
test('verification asks Auth for user, claims pilot access and exposes no token',async()=>{const s=setup();await s.login();assert.deepEqual(Object.keys(s.c.user()),['id']);assert.equal(s.c.user().id,uid);assert.equal(s.calls.length,3);assert(s.calls[1].url.endsWith('/auth/v1/user'));assert.equal(s.calls[1].headers.Authorization,'Bearer test-token');assert(s.calls[2].url.endsWith('/rest/v1/rpc/fk_claim_first_pilot'));});
test('anonymous shared access rejected before transport',async()=>{const s=setup();await assert.rejects(s.c.communities(),e=>e.code==='AUTH_REQUIRED');assert.equal(s.calls.length,0);});
test('shared requests separate user JWT and publishable key',async()=>{const s=setup();await s.login();await s.c.communities();const q=s.calls.at(-1);assert.equal(q.headers.apikey,cfg.publishableKey);assert.equal(q.headers.Authorization,'Bearer test-token');});
test('profile RPC has no caller-selectable user id',async()=>{const s=setup();await s.login();await s.c.saveProfile({id:cid,name:'Alice',skills:'',about:'',listed:false});const v=JSON.parse(s.calls.at(-1).body);assert.deepEqual(Object.keys(v).sort(),['p_about','p_listed','p_name','p_skills']);assert.equal(v.p_listed,false);});
test('post RPC has no caller-selectable author',async()=>{const s=setup();await s.login();await s.c.publish(cid,'A plan');assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_community:cid,p_body:'A plan'});});
test('bad IDs and oversized text rejected before transport',async()=>{const s=setup();await s.login();assert.throws(()=>s.c.join('x&user_id=eq.other'),e=>e.code==='INVALID_INPUT');assert.throws(()=>s.c.publish(cid,'x'.repeat(3001)),e=>e.code==='INVALID_INPUT');assert.equal(s.calls.length,3);});
test('bootstrap denial clears the new session',async()=>{const s=setup(url=>url.endsWith('/rpc/fk_claim_first_pilot')?json({},403):null);await assert.rejects(s.login(),e=>e.code==='DENIED');assert.equal(s.c.user(),null);});
test('logout clears memory even on revocation failure',async()=>{const s=setup(url=>url.includes('/logout')?json({error:'SECRET DETAIL'},500):null);await s.login();await assert.rejects(s.c.logout(),e=>e.code==='REQUEST_FAILED'&&!e.message.includes('SECRET'));assert.equal(s.c.user(),null);await assert.rejects(s.c.communities(),e=>e.code==='AUTH_REQUIRED');});
test('expired session requires new login',async()=>{const s=setup();await s.login();s.expire();assert.equal(s.c.user(),null);await assert.rejects(s.c.communities(),e=>e.code==='AUTH_REQUIRED');});
test('401 clears session',async()=>{const s=setup(url=>url.includes('/rest/')?json({},401):null);await s.login();await assert.rejects(s.c.communities(),e=>e.code==='AUTH_REQUIRED');assert.equal(s.c.user(),null);});
test('403 differs from a successful empty directory',async()=>{const s=setup(url=>url.includes('/rest/')?json({},403):null);await s.login();await assert.rejects(s.c.directory(),e=>e.code==='DENIED');});
test('429 does not replay mutations',async()=>{const s=setup(url=>url.endsWith('/otp')?json({},429):null);await assert.rejects(s.c.requestCode('test@example.test'),e=>e.code==='RATE_LIMIT');assert.equal(s.calls.length,1);});
test('HTML rejected as API data',async()=>{const s=setup(url=>url.includes('/rest/')?new Response('<html>error</html>'):null);await s.login();await assert.rejects(s.c.communities(),e=>e.code==='INVALID_RESPONSE');});
test('malformed data not treated as empty',async()=>{const s=setup(url=>url.includes('/rest/')?json({error:'broken'}):null);await s.login();await assert.rejects(s.c.communities(),e=>e.code==='INVALID_RESPONSE');});
test('inflight reply cannot restore data after logout',async()=>{let release;const s=setup(url=>url.includes('/rest/')?new Promise(r=>release=()=>r(json([{name:'Private'}]))):null);await s.login();const pending=s.c.communities();await s.c.logout();release();await assert.rejects(pending,e=>e.code==='STALE');assert.equal(s.c.user(),null);});
test('no persistent tokens or implicit local draft upload',async()=>{const code=await readFile('network-client.js','utf8');assert(!/localStorage|sessionStorage|indexedDB|sendBeacon/.test(code.replace(/\/\/[^\n]*/g,'')));assert(!/result\.refresh_token/.test(code));assert(!code.includes('folkoop-workspace-v1'));});
