import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const ctx=vm.createContext({URL,AbortController,setTimeout,clearTimeout});
vm.runInContext(await readFile('network-client.js','utf8'),ctx);
const N=ctx.FolkoopNetwork;
const cfg={enabled:true,url:'https://abcdefghijklmnopqrst.supabase.co',publishableKey:'sb_publishable_example_for_tests_only'};
const uid='11111111-1111-4111-8111-111111111111',cid='22222222-2222-4222-8222-222222222222';
const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json'}});
function setup(extra){const calls=[];let now=1000;
 const c=N.client(cfg,{clock:()=>now,transport:async(url,o)=>{calls.push({url,...o});if(extra){const r=await extra(url,o);if(r)return r;}
 if(url.endsWith('/verify'))return json({access_token:'test-token',expires_in:100,refresh_token:'never-store'});
 if(url.endsWith('/user'))return json({id:uid,email:'synthetic@example.test'});
 if(url.includes('/rpc/'))return json(null);return json([]);
 }});return{c,calls,expire(){now+=200000;},login:()=>c.verify('synthetic@example.test','123456')};}
test('disabled configuration never sends requests',async()=>{const c=N.client({enabled:false},{transport:()=>{throw Error('MUST_NOT_CALL');}});assert(!c.enabled);await assert.rejects(c.requestCode('test@example.test'),e=>e.code==='DISABLED');});
test('configuration fails closed without HTTPS project and publishable key',()=>{for(const change of [{url:'http://abcdefghijklmnopqrst.supabase.co'},{url:'https://attacker.example'},{url:cfg.url+'/other'},{url:cfg.url+'?token=x'},{url:'https://x@abcdefghijklmnopqrst.supabase.co'},{publishableKey:'sb_secret_DO_NOT_SHIP'},{publishableKey:'eyJlegacyJWT'}])assert.throws(()=>N.client({...cfg,...change}),e=>e.code==='CONFIG');});
test('OTP bootstrap may create the first Auth user without secrets in URL',async()=>{const s=setup();await s.c.requestCode('test@example.test');const r=s.calls[0];assert.equal(r.method,'POST');assert.equal(JSON.parse(r.body).create_user,true);assert(!r.url.includes('test@'));assert.equal(r.credentials,'omit');assert.equal(r.cache,'no-store');assert.equal(r.redirect,'error');assert(!r.headers.Authorization);});
test('bad email rejected before transport',async()=>{const s=setup();await assert.rejects(s.c.requestCode('invalid'),e=>e.code==='INVALID_INPUT');assert.equal(s.calls.length,0);});
test('bad OTP rejected before transport',async()=>{const s=setup();await assert.rejects(s.c.verify('test@example.test','abcdef'),e=>e.code==='INVALID_INPUT');assert.equal(s.calls.length,0);});
test('verification asks Auth for user, claims pilot access and exposes no token',async()=>{const s=setup();await s.login();assert.deepEqual(Object.keys(s.c.user()),['id']);assert.equal(s.c.user().id,uid);assert.equal(s.calls.length,3);assert(s.calls[1].url.endsWith('/auth/v1/user'));assert.equal(s.calls[1].headers.Authorization,'Bearer test-token');assert(s.calls[2].url.endsWith('/rest/v1/rpc/fk_claim_first_pilot'));});
test('anonymous shared access rejected before transport',async()=>{const s=setup();await assert.rejects(s.c.communities(),e=>e.code==='AUTH_REQUIRED');assert.equal(s.calls.length,0);});
test('shared requests separate user JWT and publishable key',async()=>{const s=setup();await s.login();await s.c.communities();const q=s.calls.at(-1);assert.equal(q.headers.apikey,cfg.publishableKey);assert.equal(q.headers.Authorization,'Bearer test-token');});
test('profile RPC has no caller-selectable user id',async()=>{const s=setup();await s.login();await s.c.saveProfile({id:cid,name:'Alice',skills:'',about:'',listed:false});const v=JSON.parse(s.calls.at(-1).body);assert.deepEqual(Object.keys(v).sort(),['p_about','p_listed','p_name','p_skills']);assert.equal(v.p_listed,false);});
test('post RPC has no caller-selectable author',async()=>{const s=setup();await s.login();await s.c.publish(cid,'A plan');assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_community:cid,p_body:'A plan'});});
test('bad IDs and oversized text rejected before transport',async()=>{const s=setup();await s.login();assert.throws(()=>s.c.join('x&user_id=eq.other'),e=>e.code==='INVALID_INPUT');assert.throws(()=>s.c.publish(cid,'x'.repeat(3001)),e=>e.code==='INVALID_INPUT');assert.equal(s.calls.length,3);});
test('bootstrap denial clears the new session',async()=>{const s=setup(url=>url.endsWith('/rpc/fk_claim_first_pilot')?json({},403):null);await assert.rejects(s.login(),e=>e.code==='DENIED');assert.equal(s.c.user(),null);});
test('logout clears memory even on revocation failure',async()=>{const s=setup(url=>url.includes('/logout')?json({error:'SECRET DETAIL'},500):null);await s.login();await assert.rejects(s.c.logout(),e=>e.code==='REQUEST_FAILED'&&!e.message.includes('SECRET'));assert.equal(s.c.user(),null);await assert.rejects(s.c.communities(),e=>e.code==='AUTH_REQUIRED');});
test('expired session requires new login',async()=>{const s=setup();await s.login();s.expire();assert.equal(s.c.user(),null);await assert.rejects(s.c.communities(),e=>e.code==='AUTH_REQUIRED');});
test('401 clears session',async()=>{const s=setup(url=>url.includes('/rest/v1/fk_communities')?json({},401):null);await s.login();await assert.rejects(s.c.communities(),e=>e.code==='AUTH_REQUIRED');assert.equal(s.c.user(),null);});
test('403 differs from a successful empty directory',async()=>{const s=setup(url=>url.includes('/rest/v1/fk_profiles?select=id,name,skills,about&listed=eq.true')?json({},403):null);await s.login();await assert.rejects(s.c.directory(),e=>e.code==='DENIED');});
test('429 does not replay mutations',async()=>{const s=setup(url=>url.endsWith('/otp')?json({},429):null);await assert.rejects(s.c.requestCode('test@example.test'),e=>e.code==='RATE_LIMIT');assert.equal(s.calls.length,1);});
test('HTML rejected as API data',async()=>{const s=setup(url=>url.includes('/rest/v1/fk_communities')?new Response('<html>error</html>'):null);await s.login();await assert.rejects(s.c.communities(),e=>e.code==='INVALID_RESPONSE');});
test('malformed data not treated as empty',async()=>{const s=setup(url=>url.includes('/rest/v1/fk_communities')?json({error:'broken'}):null);await s.login();await assert.rejects(s.c.communities(),e=>e.code==='INVALID_RESPONSE');});
test('inflight reply cannot restore data after logout',async()=>{let release;const s=setup(url=>url.includes('/rest/v1/fk_communities')?new Promise(r=>release=()=>r(json([{name:'Private'}]))):null);await s.login();const pending=s.c.communities();await s.c.logout();release();await assert.rejects(pending,e=>e.code==='STALE');assert.equal(s.c.user(),null);});

test('direct chat RPC derives sender on server and accepts only UUID target',async()=>{const s=setup();await s.login();await s.c.startDirect(cid);const q=s.calls.at(-1);assert(q.url.endsWith('/rest/v1/rpc/fk_start_direct'));assert.deepEqual(JSON.parse(q.body),{p_other:cid});assert.throws(()=>s.c.startDirect('not-a-uuid'),e=>e.code==='INVALID_INPUT');});
test('group chat RPC validates title and deduplicates member ids',async()=>{const s=setup();await s.login();await s.c.createGroupChat('Workshop',[cid,cid]);const q=s.calls.at(-1);assert.deepEqual(JSON.parse(q.body),{p_title:'Workshop',p_members:[cid]});assert.throws(()=>s.c.createGroupChat('x',[cid]),e=>e.code==='INVALID_INPUT');assert.throws(()=>s.c.createGroupChat('Valid',[]),e=>e.code==='INVALID_INPUT');});
test('message RPC has no caller-selectable author and enforces body bound',async()=>{const s=setup();await s.login();await s.c.sendMessage(cid,'hello');assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_conversation:cid,p_body:'hello'});assert.throws(()=>s.c.sendMessage(cid,''),e=>e.code==='INVALID_INPUT');assert.throws(()=>s.c.sendMessage(cid,'x'.repeat(4001)),e=>e.code==='INVALID_INPUT');});
test('message report and membership actions validate ids locally',async()=>{const s=setup();await s.login();await s.c.reportMessage(cid,'abuse');assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_message:cid,p_reason:'abuse'});assert.throws(()=>s.c.acceptChat('x'),e=>e.code==='INVALID_INPUT');assert.throws(()=>s.c.removeChatMember(cid,'x'),e=>e.code==='INVALID_INPUT');});


test('cooperation creation separates purchase quantity from other kinds',async()=>{const s=setup();await s.login();await s.c.createCooperation({kind:'purchase',title:'Firewood',description:'Together',location:'Göteborg',targetQuantity:'30',unit:'m3'});assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_kind:'purchase',p_title:'Firewood',p_description:'Together',p_location:'Göteborg',p_target_quantity:30,p_unit:'m3'});await s.c.createCooperation({kind:'project',title:'Workshop',description:'',location:'',targetQuantity:'99',unit:'kg'});assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_kind:'project',p_title:'Workshop',p_description:'',p_location:'',p_target_quantity:null,p_unit:''});});
test('cooperation client rejects bad kind, quantity and ids before transport',async()=>{const s=setup();await s.login();assert.throws(()=>s.c.createCooperation({kind:'bad',title:'Good title'}),e=>e.code==='INVALID_INPUT');assert.throws(()=>s.c.createCooperation({kind:'purchase',title:'Good title',targetQuantity:'0',unit:'kg'}),e=>e.code==='INVALID_INPUT');assert.throws(()=>s.c.joinCooperation('x'),e=>e.code==='INVALID_INPUT');});
test('project tasks and updates never accept caller-selected author',async()=>{const s=setup();await s.login();await s.c.addCooperationUpdate(cid,'Progress');assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid,p_body:'Progress'});await s.c.createProjectTask(cid,{title:'Task',details:'Details',assignee:null});assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid,p_title:'Task',p_details:'Details',p_assignee:null});});
test('purchase commitment uses zero only as explicit removal',async()=>{const s=setup();await s.login();await s.c.setPurchaseCommitment(cid,'4.5','delivery');assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid,p_quantity:4.5,p_note:'delivery'});await s.c.setPurchaseCommitment(cid,0,'');assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid,p_quantity:0,p_note:''});assert.throws(()=>s.c.setPurchaseCommitment(cid,-1,''),e=>e.code==='INVALID_INPUT');});


test('purchase offer RPC normalizes currency and pickup fee',async()=>{const s=setup();await s.login();await s.c.savePurchaseOffer(cid,{unitPrice:'5.25',currency:'sek',minQuantity:'100',availableQuantity:'1500',deliveryMode:'pickup',deliveryFee:'999',leadTimeDays:'2',validUntil:'2030-01-01',note:'test'});assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid,p_unit_price:5.25,p_currency:'SEK',p_min_quantity:100,p_available_quantity:1500,p_delivery_mode:'pickup',p_delivery_fee:0,p_lead_time_days:2,p_valid_until:'2030-01-01',p_note:'test'});});
test('purchase offer client validates price, currency and delivery mode before transport',async()=>{const s=setup();await s.login();assert.throws(()=>s.c.savePurchaseOffer(cid,{unitPrice:0,currency:'SEK',minQuantity:1,deliveryMode:'pickup'}),e=>e.code==='INVALID_INPUT');assert.throws(()=>s.c.savePurchaseOffer(cid,{unitPrice:1,currency:'SE',minQuantity:1,deliveryMode:'pickup'}),e=>e.code==='INVALID_INPUT');assert.throws(()=>s.c.savePurchaseOffer(cid,{unitPrice:1,currency:'SEK',minQuantity:1,deliveryMode:'drone'}),e=>e.code==='INVALID_INPUT');});
test('owner choice and provider withdrawal use narrow RPC payloads',async()=>{const s=setup();await s.login();await s.c.choosePurchaseOffer(cid,uid);assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid,p_offer:uid});await s.c.choosePurchaseOffer(cid,null);assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid,p_offer:null});await s.c.withdrawPurchaseOffer(cid);assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid});});
test('supplier offer report validates visible offer id and reason locally',async()=>{const s=setup();await s.login();await s.c.reportPurchaseOffer(cid,'bad terms');assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_offer:cid,p_reason:'bad terms'});assert.throws(()=>s.c.reportPurchaseOffer('x','reason'),e=>e.code==='INVALID_INPUT');assert.throws(()=>s.c.reportPurchaseOffer(cid,'x'),e=>e.code==='INVALID_INPUT');});


test('purchase lifecycle confirmation uses explicit timestamp and boolean decision',async()=>{const s=setup();await s.login();await s.c.startPurchaseConfirmation(cid,'2030-01-02T12:30:00Z');assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid,p_deadline:'2030-01-02T12:30:00.000Z'});await s.c.confirmPurchaseParticipation(cid,false,'not this round');assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid,p_confirm:false,p_note:'not this round'});assert.throws(()=>s.c.confirmPurchaseParticipation(cid,'yes','x'),e=>e.code==='INVALID_INPUT');});
test('external order marker sends no payment or provider identity',async()=>{const s=setup();await s.login();await s.c.markPurchaseOrdered(cid,{reference:'EXT-1',expectedDelivery:'2030-01-04T10:00:00Z',note:'external only',pickupPlace:'Center',pickupStart:'2030-01-05T10:00:00Z',pickupEnd:'2030-01-05T12:00:00Z'});assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid,p_reference:'EXT-1',p_expected_delivery:'2030-01-04T10:00:00.000Z',p_note:'external only',p_pickup_place:'Center',p_pickup_start:'2030-01-05T10:00:00.000Z',p_pickup_end:'2030-01-05T12:00:00.000Z'});assert.throws(()=>s.c.markPurchaseOrdered(cid,{pickupStart:'2030-01-05T12:00:00Z',pickupEnd:'2030-01-05T10:00:00Z'}),e=>e.code==='INVALID_INPUT');});
test('delivery, collection, finish and cancellation use narrow lifecycle RPCs',async()=>{const s=setup();await s.login();await s.c.markPurchaseDelivered(cid,'arrived');assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid,p_note:'arrived'});await s.c.markPurchaseCollected(cid,true,'picked up');assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid,p_collected:true,p_note:'picked up'});await s.c.finishPurchase(cid,'completed with note');assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid,p_result_note:'completed with note'});await s.c.cancelPurchase(cid,'supplier unavailable');assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid,p_reason:'supplier unavailable'});assert.throws(()=>s.c.cancelPurchase(cid,'x'),e=>e.code==='INVALID_INPUT');});


test('linked cooperation chat and activity reads use narrow endpoints',async()=>{const s=setup();await s.login();await s.c.cooperationChats();assert(s.calls.at(-1).url.includes('/rest/v1/fk_cooperation_chats?'));await s.c.cooperationActivity(cid);assert(s.calls.at(-1).url.includes('cooperation_id=eq.'+cid));});
test('activity and chat inbox RPCs require array responses',async()=>{const s=setup();await s.login();await s.c.chatInbox();assert(s.calls.at(-1).url.endsWith('/rest/v1/rpc/fk_chat_inbox'));await s.c.activityInbox();assert(s.calls.at(-1).url.endsWith('/rest/v1/rpc/fk_activity_inbox'));const bad=setup(url=>url.endsWith('/rpc/fk_chat_inbox')?json({bad:true}):null);await bad.login();await assert.rejects(bad.c.chatInbox(),e=>e.code==='INVALID_RESPONSE');});
test('mark cooperation read validates cooperation id locally',async()=>{const s=setup();await s.login();await s.c.markCooperationRead(cid);assert.deepEqual(JSON.parse(s.calls.at(-1).body),{p_cooperation:cid});assert.throws(()=>s.c.markCooperationRead('bad'),e=>e.code==='INVALID_INPUT');});

test('no persistent tokens or implicit local draft upload',async()=>{const code=await readFile('network-client.js','utf8');assert(!/localStorage|sessionStorage|indexedDB|sendBeacon/.test(code.replace(/\/\/[^\n]*/g,'')));assert(!/result\.refresh_token/.test(code));assert(!code.includes('folkoop-workspace-v1'));});
