import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const sandbox={};
vm.runInNewContext(readFileSync('apps/web/resource-planning-lifecycle.js','utf8'),sandbox);
const api=sandbox.FolkoopResourceLifecycle;
const A='11111111-1111-4111-8111-111111111111';
const B='22222222-2222-4222-8222-222222222222';
const row=(id=A)=>({id,quantity:'0.125',conditions:'<b>plain data</b>'});
const page=(v={})=>({schema_version:1,kind:'requirements',scope:'own_resource_planning_only',snapshot:false,records:[row()],has_more:false,next_cursor:null,...v});
const rejects=(fn,code)=>assert.throws(fn,e=>e.code===code);
test('API frozen and has no network or storage dependencies',()=>assert.ok(Object.isFrozen(api)));
test('requirement removal sends only named IDs and expected version',()=>{
 const a=api.removeRequirementArgs(A,B,2);assert.equal(a.p_project,A);assert.equal(a.p_id,B);assert.equal(a.p_expected_revision,2);assert.equal(Object.keys(a).length,3);assert.ok(Object.isFrozen(a));
});
test('availability removal reuses resource identity',()=>assert.equal(api.removeAvailabilityArgs(A,3).p_resource,A));
test('generation lookup never accepts another user identity',()=>assert.equal(Object.keys(api.availabilityRevisionArgs(A)).length,1));
for(const r of [0,-1,null,'1',1.5,2147483647,NaN])test(`removal revision rejected: ${String(r)}`,()=>rejects(()=>api.removeAvailabilityArgs(A,r),'INVALID_REVISION'));
test('bad requirement ID rejected',()=>rejects(()=>api.removeRequirementArgs(A,'local-draft',1),'INVALID_ID'));
test('export defaults bounded, first-page cursor explicit',()=>{const a=api.exportArgs('requirements');assert.equal(a.p_limit,100);assert.equal(a.p_after,null);});
test('next page uses UUID cursor and not offset',()=>{const a=api.exportArgs('availability',B,1);assert.equal(a.p_after,B);assert.equal(a.p_limit,1);assert.equal(a.offset,undefined);});
for(const size of [0,101,-1,1.5,'10',null])test(`bad export limit rejected: ${String(size)}`,()=>rejects(()=>api.exportArgs('requirements',null,size),'INVALID_PAGE_SIZE'));
test('arbitrary table export denied',()=>rejects(()=>api.exportArgs('pilots'),'INVALID_EXPORT_KIND'));
test('empty cursor is not silently first page',()=>rejects(()=>api.exportArgs('requirements',''),'INVALID_ID'));
test('valid page preserves exact decimal text and plain conditions',()=>{const p=api.exportPage(page(),'requirements');assert.equal(p.records[0].quantity,'0.125');assert.equal(p.records[0].conditions,'<b>plain data</b>');assert.ok(Object.isFrozen(p.records));});
test('caller object is not mutated',()=>{const input=page();const before=JSON.stringify(input);api.exportPage(input,'requirements');assert.equal(JSON.stringify(input),before);});
test('empty final page accepted',()=>assert.equal(api.exportPage(page({records:[]}),'requirements').records.length,0));
test('more flag requires nonempty page',()=>rejects(()=>api.exportPage(page({records:[],has_more:true,next_cursor:A}),'requirements'),'INVALID_EXPORT_CURSOR'));
test('more cursor must equal final included key',()=>rejects(()=>api.exportPage(page({has_more:true,next_cursor:B}),'requirements'),'INVALID_EXPORT_CURSOR'));
test('terminal page requires null cursor',()=>rejects(()=>api.exportPage(page({next_cursor:A}),'requirements'),'INVALID_EXPORT_CURSOR'));
test('valid continuation accepted',()=>assert.equal(api.exportPage(page({has_more:true,next_cursor:A}),'requirements').next_cursor,A));
test('duplicate keys rejected',()=>rejects(()=>api.exportPage(page({records:[row(),row()]}),'requirements'),'INVALID_EXPORT_ORDER'));
test('out-of-order keys rejected',()=>rejects(()=>api.exportPage(page({records:[row(B),row(A)]}),'requirements'),'INVALID_EXPORT_ORDER'));
test('numeric quantities rejected instead of silently rounding',()=>rejects(()=>api.exportPage(page({records:[{id:A,quantity:0.125}]}),'requirements'),'INVALID_EXPORT_QUANTITY'));
test('exponent quantities rejected',()=>rejects(()=>api.exportPage(page({records:[{id:A,quantity:'1e3'}]}),'requirements'),'INVALID_EXPORT_QUANTITY'));
test('unexpected dataset rejected',()=>rejects(()=>api.exportPage(page(),'availability'),'INVALID_EXPORT_PAGE'));
test('complete-account claim rejected',()=>rejects(()=>api.exportPage(page({scope:'complete_account'}),'requirements'),'INVALID_EXPORT_PAGE'));
test('snapshot claim rejected',()=>rejects(()=>api.exportPage(page({snapshot:true}),'requirements'),'INVALID_EXPORT_PAGE'));
test('wrong schema version rejected',()=>rejects(()=>api.exportPage(page({schema_version:2}),'requirements'),'INVALID_EXPORT_PAGE'));
test('truthy string flag rejected',()=>rejects(()=>api.exportPage(page({has_more:'false'}),'requirements'),'INVALID_EXPORT_PAGE'));
test('unbounded page rejected',()=>rejects(()=>api.exportPage(page({records:Array(101).fill(row())}),'requirements'),'INVALID_EXPORT_PAGE'));
test('availability pages use canonical resource_id',()=>{const p=api.exportPage(page({kind:'availability',records:[{resource_id:A,quantity:'0'}]}),'availability');assert.equal(p.records[0].resource_id,A);});
